import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,readdirSync,existsSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {spawnSync} from 'node:child_process';import {DatabaseSync} from 'node:sqlite';
const server=resolve('scripts/hermit-mcp-server.mjs');
test('background uncaught failure after transport startup is captured once',t=>{const root=mkdtempSync(join(tmpdir(),'hermit-background-'));t.after(()=>rmSync(root,{recursive:true,force:true}));const loader=join(root,'loader.mjs');const source="export class StdioServerTransport {start(){setTimeout(()=>{throw Error('SENTINEL_PRIVATE_BACKGROUND')},30);return Promise.resolve()} send(){} close(){}}";writeFileSync(loader,`import {registerHooks} from 'node:module';registerHooks({resolve(s,c,next){if(s==='@modelcontextprotocol/sdk/server/stdio.js')return {url:'data:text/javascript,'+encodeURIComponent(${JSON.stringify(source)}),shortCircuit:true};return next(s,c);}});`);const r=spawnSync(process.execPath,['--import',pathToFileURL(loader).href,server],{cwd:root,env:{...process.env,HERMIT_DATA_DIR:root,HERMIT_DB_PATH:'',HERMIT_DIAGNOSTICS:'errors',HERMIT_STORAGE:'v8',HERMIT_USER_CWD:'',HERMIT_PROJECT_CWD:'',CLAUDE_PROJECT_DIR:''},encoding:'utf8',timeout:10000});assert.equal(r.status,1,r.stderr);const files=readdirSync(join(root,'crash-spool'));assert.equal(files.length,1);assert.equal(JSON.parse(readFileSync(join(root,'crash-spool',files[0]),'utf8')).metadata.phase,'background');assert.ok(!r.stderr.includes('SENTINEL_PRIVATE_BACKGROUND'));});
for(const stage of ['import','open','initialize','ready'])test('boot failure at '+stage+' is captured once and sanitized',t=>{
 const root=mkdtempSync(join(tmpdir(),'hermit-boot-')),data=join(root,'data');mkdirSync(data);t.after(()=>rmSync(root,{recursive:true,force:true}));const targets={import:'@modelcontextprotocol/sdk/server/mcp.js',open:'./lib/storage/brain-store.mjs',initialize:'./lib/memory-service.mjs',ready:'@modelcontextprotocol/sdk/server/stdio.js'};
 const source=stage==='import'?`throw Error('SENTINEL_PRIVATE_BOOT')`:stage==='open'?`export class BrainStore {constructor(){throw Error('SENTINEL_PRIVATE_BOOT')}}`:stage==='initialize'?`export class MemoryService {constructor(){throw Error('SENTINEL_PRIVATE_BOOT')}}`:`export class StdioServerTransport {constructor(){throw Error('SENTINEL_PRIVATE_BOOT')}}`;
 const loader=join(root,'loader.mjs');writeFileSync(loader,`import {registerHooks} from 'node:module';registerHooks({resolve(specifier,context,next){if(specifier===${JSON.stringify(targets[stage])})return {url:'data:text/javascript,'+encodeURIComponent(${JSON.stringify(source)}),shortCircuit:true};return next(specifier,context);}});`);
 const r=spawnSync(process.execPath,['--import',pathToFileURL(loader).href,server],{cwd:root,env:{...process.env,HERMIT_DATA_DIR:data,HERMIT_DB_PATH:'',HERMIT_STORAGE:'v8',HERMIT_DIAGNOSTICS:'errors',HERMIT_PROJECT_CWD:'',HERMIT_USER_CWD:'',CLAUDE_PROJECT_DIR:''},encoding:'utf8',timeout:10000});assert.equal(r.status,1,r.stderr);assert.ok(!r.stderr.includes('SENTINEL_PRIVATE_BOOT'));const files=readdirSync(join(data,'crash-spool')).filter(n=>n.endsWith('.json'));assert.equal(files.length,1);const c=JSON.parse(readFileSync(join(data,'crash-spool',files[0]),'utf8'));assert.equal(c.metadata.phase,stage);assert.match(r.stderr,new RegExp(c.context.operationId));assert.ok(!JSON.stringify(c).includes('SENTINEL_PRIVATE_BOOT'));
});
test('old schema stays byte-identical; full spool discloses degradation; off writes nothing',t=>{const root=mkdtempSync(join(tmpdir(),'hermit-boot-policy-'));t.after(()=>rmSync(root,{recursive:true,force:true}));const dbPath=join(root,'brain.db'),db=new DatabaseSync(dbPath);db.exec('PRAGMA user_version=7; CREATE TABLE old_data(value TEXT)');db.close();const before=readFileSync(dbPath);const env={...process.env,HERMIT_DATA_DIR:root,HERMIT_DB_PATH:'',HERMIT_STORAGE:'v8',HERMIT_DIAGNOSTICS:'off'};let r=spawnSync(process.execPath,[server],{env,encoding:'utf8'});assert.equal(r.status,1);assert.equal(existsSync(join(root,'crash-spool')),false);assert.deepEqual(readFileSync(dbPath),before);mkdirSync(join(root,'crash-spool'));for(let i=0;i<32;i++)writeFileSync(join(root,'crash-spool',i+'.tmp'),'{}');r=spawnSync(process.execPath,[server],{env:{...env,HERMIT_DIAGNOSTICS:'errors'},encoding:'utf8'});assert.equal(r.status,1);assert.match(r.stderr,/"diagnosticsDegraded":true/);assert.equal(readdirSync(join(root,'crash-spool')).length,32);assert.deepEqual(readFileSync(dbPath),before);});
