import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,readFileSync,rmSync,renameSync,mkdirSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {ensureFreshCodeIndex,resolveCodeCache} from '../scripts/lib/code-intel/code-index-service.mjs';
import {registerV8CodeTools} from '../scripts/lib/v8-code-tools.mjs';
import {readCodeGraph} from '../scripts/lib/code-intel/code-io.mjs';
test('index follows uncommitted/untracked/delete changes and preserves last-good on failure',async t=>{
 const root=mkdtempSync(join(tmpdir(),'v8-codefresh-'));t.after(()=>rmSync(root,{recursive:true,force:true}));const data=join(root,'.hermit','code');
 writeFileSync(join(root,'a.mjs'),'export function alpha() {return 1;}');await ensureFreshCodeIndex(root,data);
 assert.ok(readCodeGraph(data).searchSymbols('alpha').length);writeFileSync(join(root,'a.mjs'),'export function beta() {return 2;}');await ensureFreshCodeIndex(root,data);assert.equal(readCodeGraph(data).searchSymbols('alpha').length,0);
 writeFileSync(join(root,'b.mjs'),'export function gamma() {return 3;}');await ensureFreshCodeIndex(root,data);assert.ok(readCodeGraph(data).searchSymbols('gamma').length);rmSync(join(root,'a.mjs'));await ensureFreshCodeIndex(root,data);assert.equal(readCodeGraph(data).searchSymbols('beta').length,0);
 const before=readFileSync(join(data,'code-symbols.jsonl'));writeFileSync(join(root,'b.mjs'),'export function delta() {}');await assert.rejects(ensureFreshCodeIndex(root,data,{build:async()=>{throw new Error('worker failure');}}));assert.deepEqual(readFileSync(join(data,'code-symbols.jsonl')),before);
});
test('malformed source refuses publication and retains verified graph',async t=>{const root=mkdtempSync(join(tmpdir(),'v8-codeparse-'));t.after(()=>rmSync(root,{recursive:true,force:true}));const data=join(root,'.hermit','code');writeFileSync(join(root,'a.mjs'),'export function valid() {}');await ensureFreshCodeIndex(root,data);const before=readFileSync(join(data,'code-symbols.jsonl'));writeFileSync(join(root,'a.mjs'),'export function broken( {');await assert.rejects(ensureFreshCodeIndex(root,data),/HERMIT_INDEX_PARSE_FAILED/);assert.deepEqual(readFileSync(join(data,'code-symbols.jsonl')),before);});
test('tool freshness uses central cache and excludes in-project data artifacts',async t=>{const root=mkdtempSync(join(tmpdir(),'v8-codepaths-'));t.after(()=>rmSync(root,{recursive:true,force:true}));const dataRoot=join(root,'runtime-data');mkdirSync(dataRoot);writeFileSync(join(root,'a.mjs'),'export function actual() {}');writeFileSync(join(dataRoot,'junk.mjs'),'export function malformed( {');const handlers={};registerV8CodeTools({tool(name,description,schema,fn){handlers[name]=fn;}},{sessionRootPath:root},{dataRoot});await handlers.hermit_index({});const result=JSON.parse((await handlers.hermit_detect_changes({})).content[0].text);assert.equal(result.stale,false);assert.deepEqual(Object.keys(result.manifest.files),['a.mjs']);assert.ok(readCodeGraph(resolveCodeCache(root,dataRoot)).searchSymbols('actual').length);});
