import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,readFileSync,rmSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {BrainStore} from '../scripts/lib/storage/brain-store.mjs';import {DiagnosticsStore} from '../scripts/lib/diagnostics/store.mjs';import {upgradePlan,applyUpgrade} from '../scripts/lib/maintenance/upgrade-service.mjs';import {diagnosticBundle} from '../scripts/lib/diagnostics/bundle.mjs';
test('revision 2 upgrades explicitly to cause/session diagnostics without losing knowledge or totals',async t=>{
 const root=mkdtempSync(join(tmpdir(),'hermit-diag-upgrade-')),dbPath=join(root,'brain.db');t.after(()=>rmSync(root,{recursive:true,force:true}));let brain=new BrainStore({dbPath}),diagnostics=new DiagnosticsStore({brainStore:brain});const entity=brain.createEntity({name:'TECH:Preserve',entityType:'tech-config'}).entity;diagnostics.record({code:'HERMIT_TEST_FAILURE'});diagnostics.close();
 for(const column of ['operation','error_name','signature','frames_json'])brain.db.exec('ALTER TABLE diag_fingerprint DROP COLUMN '+column);brain.db.exec("ALTER TABLE diag_operation DROP COLUMN session_id; ALTER TABLE diag_import DROP COLUMN fingerprint_id; DROP TABLE diag_secret; UPDATE diag_meta SET value=1 WHERE key='schema_version'; UPDATE schema_meta SET value='2' WHERE key='revision'");brain.close();
 const bytes=readFileSync(dbPath);assert.throws(()=>new BrainStore({dbPath}),{code:'HERMIT_UPGRADE_REQUIRED'});assert.deepEqual(readFileSync(dbPath),bytes);
 const plan=upgradePlan(dbPath);assert.equal(plan.fromRevision,2);assert.equal(plan.toRevision,3);await applyUpgrade(dbPath,{confirmation:JSON.stringify(plan)});
 brain=new BrainStore({dbPath});diagnostics=new DiagnosticsStore({brainStore:brain});try{assert.equal(brain.getEntity({id:entity.id}).name,'TECH:Preserve');assert.equal(diagnostics.summary().failures,1);const salt=diagnostics.faultSalt();assert.equal(salt.length,32);assert.ok(!JSON.stringify(diagnosticBundle(diagnostics)).includes(salt.toString('hex')));
 const sessionId='11111111-1111-7111-8111-111111111111';diagnostics.session(sessionId);diagnostics.record({code:'HERMIT_RUNTIME_ERROR',operation:'hermit_index',errorName:'TypeError',signature:'a'.repeat(64),frames:['scripts/lib/indexer.mjs#build']},{sessionId,operationId:'22222222-2222-7222-8222-222222222222'});assert.equal(diagnostics.operations()[0].session_id,sessionId);const row=diagnostics.list().find(r=>r.operation==='hermit_index');assert.deepEqual(row.frames,['scripts/lib/indexer.mjs#build']);assert.equal(row.errorName,'TypeError');
 }finally{diagnostics.close();brain.close();}
});
