import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync,rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { BrainStore } from '../scripts/lib/storage/brain-store.mjs';
import { DiagnosticsStore,DIAGNOSTICS_SCHEMA_SQL } from '../scripts/lib/diagnostics/store.mjs';
import { pruneDiagnostics } from '../scripts/lib/diagnostics/retention.mjs';
import { diagnosticBundle } from '../scripts/lib/diagnostics/bundle.mjs';
import { promoteIncident } from '../scripts/lib/diagnostics/incident-promotion.mjs';
function setup(t){const root=mkdtempSync(join(tmpdir(),'hermit-diag-maint-')),brain=new BrainStore({dbPath:join(root,'brain.db')});brain.db.exec(DIAGNOSTICS_SCHEMA_SQL);const store=new DiagnosticsStore({brainStore:brain});t.after(()=>{store.close();brain.close();rmSync(root,{recursive:true,force:true});});return {root,brain,store};}
test('retention preview is read only; pruning preserves totals and active fingerprints',t=>{const {store}=setup(t);for(let i=0;i<20;i++)store.record({code:'HERMIT_RUNTIME_ERROR'});const before=store.summary();assert.equal(pruneDiagnostics(store,{dryRun:true,occurrenceLimit:1}).apply,false);assert.equal(store.samples(store.list()[0].id).length,5);pruneDiagnostics(store,{occurrenceLimit:1});assert.equal(store.samples(store.list()[0].id).length,1);assert.deepEqual(store.summary(),before);assert.equal(store.list().length,1);const bundle=diagnosticBundle(store);assert.equal('occurrences' in bundle,false);});
test('incident requires explicit verified evidence and commits one relation idempotently',t=>{const {store,brain,root}=setup(t);const project=brain.createProject({name:'Fixture',rootPath:root});const domain=brain.createEntity({name:'BIZ:Fixture',entityType:'biz-domain',projectId:project.id}).entity;const {id}=store.record({code:'HERMIT_RUNTIME_ERROR'},{projectId:project.id});const evidence={symptom:'Failure',rootCause:'Root cause identified',fix:'Concrete repaired behavior',files:['src/runtime.mjs'],verification:'node --test test/fixture.test.mjs passed',projectId:project.id,projectEntityId:domain.id,name:'INCIDENT:Fixture:Runtime',confirmed:true};assert.throws(()=>promoteIncident({brainStore:brain,id,...evidence}));for(const to of ['ACKNOWLEDGED','INVESTIGATING','FIXED_PENDING_VERIFY'])store.transition(id,to,{projectId:project.id});assert.throws(()=>store.transition(id,'VERIFIED_FIXED'));store.transition(id,'VERIFIED_FIXED',{verified:true,projectId:project.id});const result=promoteIncident({brainStore:brain,id,...evidence});assert.equal(promoteIncident({brainStore:brain,id,...evidence}).entity.id,result.entity.id);assert.equal(brain.listRelations({entityId:result.entity.id}).length,1);store.record({code:'HERMIT_RUNTIME_ERROR'},{projectId:project.id});assert.equal(store.show(id,{projectId:project.id}).state,'REGRESSED');assert.equal(store.show(id,{projectId:project.id}).incident_entity_id,result.entity.id);});
