import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {spawn} from 'node:child_process';
import {BrainStore} from '../scripts/lib/storage/brain-store.mjs';import {DiagnosticsStore} from '../scripts/lib/diagnostics/store.mjs';
test('hard kill at each diagnostic write/commit boundary leaves one complete record or none',async t=>{
 const root=mkdtempSync(join(tmpdir(),'hermit-diag-crash-'));t.after(()=>rmSync(root,{recursive:true,force:true}));const script=join(root,'writer.mjs');
 writeFileSync(script,`import {DiagnosticsStore} from ${JSON.stringify(new URL('../scripts/lib/diagnostics/store.mjs',import.meta.url).href)};import {writeSync} from 'node:fs';const s=new DiagnosticsStore({dbPath:process.argv[2]});const target=process.argv[3];let writes=0;const pause=stage=>{if(stage===target){writeSync(1,'ready\\n');Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,60000);}};const exec=s.db.exec.bind(s.db);s.db.exec=sql=>{if(sql==='COMMIT')pause('before-commit');const result=exec(sql);if(sql==='COMMIT')pause('after-commit');return result;};const prepare=s.db.prepare.bind(s.db);s.db.prepare=sql=>{const statement=prepare(sql),run=statement.run.bind(statement);statement.run=(...args)=>{const result=run(...args);pause('write-'+(++writes));return result;};return statement;};s.record({code:'HERMIT_TEST_FAILURE'},{operationId:'11111111-1111-4111-8111-111111111111'},'22222222-2222-4222-8222-222222222222');s.close();`);
 for(const stage of [...Array.from({length:6},(_,i)=>'write-'+(i+1)),'before-commit','after-commit']){
  const dbPath=join(root,stage,'brain.db');new BrainStore({dbPath}).close();
  await new Promise((resolve,reject)=>{const child=spawn(process.execPath,[script,dbPath,stage],{stdio:['ignore','pipe','pipe'],windowsHide:true});let reached=false,stderr='';const timer=setTimeout(()=>{child.kill();reject(Error('Kill stage not reached: '+stage+' '+stderr));},10000);child.stderr.on('data',d=>stderr+=d);child.stdout.on('data',()=>{reached=true;child.kill('SIGKILL');});child.on('error',reject);child.on('exit',()=>{clearTimeout(timer);reached?resolve():reject(Error('Unexpected writer exit: '+stderr));});});
  const brain=new BrainStore({dbPath}),store=new DiagnosticsStore({brainStore:brain});try{const expected=stage==='after-commit'?1:0;for(const table of ['diag_import','diag_fingerprint','diag_occurrence','diag_operation','diag_bucket','diag_total'])assert.equal(store.count(table),expected,stage+': '+table);assert.equal(store.summary().failures,expected);const imported=store.record({code:'HERMIT_TEST_FAILURE'},{},'22222222-2222-4222-8222-222222222222');assert.equal(imported.duplicate,Boolean(expected));assert.equal(store.summary().failures,1);}finally{store.close();brain.close();}
 }
});
