import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,mkdirSync,writeFileSync,readFileSync,existsSync,symlinkSync} from 'node:fs';
import {tmpdir,hostname} from 'node:os';
import {join,resolve} from 'node:path';
import {spawn,spawnSync} from 'node:child_process';
import {once} from 'node:events';
import {DatabaseSync} from 'node:sqlite';
import {BrainStore} from '../scripts/lib/storage/brain-store.mjs';
import {acquireRuntimeLease,acquireMaintenanceLock,recoverMaintenanceLock} from '../scripts/lib/maintenance/maintenance-lock.mjs';
import {createBackup,verifyBackup,restoreBackup,previewRestore} from '../scripts/lib/maintenance/backup-service.mjs';
import {upgradePlan,applyUpgrade,verifyUpgrade} from '../scripts/lib/maintenance/upgrade-service.mjs';
import {previewReset,applyReset} from '../scripts/lib/maintenance/reset-service.mjs';
function fixture(t){const root=mkdtempSync(join(tmpdir(),'hermit-maintenance-'));t.after(()=>rmSync(root,{recursive:true,force:true}));writeFileSync(join(root,'.hermit-data-root.json'),JSON.stringify({owner:'hermit-graph',version:1}));const path=join(root,'brain.db');const store=new BrainStore({dbPath:path});store.createEntity({name:'TECH:Test',entityType:'tech-config',observations:['retained']});store.close();return {root,path};}
test('leases reject live and mixed runtimes; exclusive maintenance blocks admission',t=>{const {path}=fixture(t);const lease=acquireRuntimeLease(path,{version:'7'});assert.throws(()=>acquireMaintenanceLock(path),{code:'HERMIT_MIXED_RUNTIME'});lease.release();const lock=acquireMaintenanceLock(path);assert.throws(()=>acquireRuntimeLease(path),{code:'HERMIT_MAINTENANCE_ACTIVE'});assert.throws(()=>acquireMaintenanceLock(path),{code:'HERMIT_MAINTENANCE_ACTIVE'});lock.release();});
test('cross-process crash stale lease has PID death evidence',async t=>{const {path}=fixture(t);const moduleUrl=new URL('../scripts/lib/maintenance/maintenance-lock.mjs',import.meta.url).href;const child=spawn(process.execPath,['--input-type=module','-e',`import {acquireRuntimeLease} from ${JSON.stringify(moduleUrl)};acquireRuntimeLease(${JSON.stringify(path)});console.log('ready');setInterval(()=>{},1000);`],{stdio:['ignore','pipe','pipe'],windowsHide:true});t.after(()=>child.kill());await once(child.stdout,'data');assert.throws(()=>acquireMaintenanceLock(path),{code:'HERMIT_RUNTIME_ACTIVE'});const exited=once(child,'exit');child.kill();await exited;const lock=acquireMaintenanceLock(path);assert.equal(lock.evidence.length,1);assert.equal(lock.evidence[0].reason,'local PID does not exist');lock.release();});
test('malformed and live maintenance owners are never guessed stale',t=>{const {path}=fixture(t);const lock=acquireMaintenanceLock(path);assert.throws(()=>recoverMaintenanceLock(path),{code:'HERMIT_STALE_PROOF_REQUIRED'});lock.release();});
test('verified lossless backup restore with post-swap rollback injection',async t=>{const {root,path}=fixture(t);const directory=join(root,'snapshot');await createBackup(path,directory);assert.equal(verifyBackup(directory).integrity,'ok');await assert.rejects(createBackup(path,directory),{code:'HERMIT_BACKUP_EXISTS'});const store=new BrainStore({dbPath:path});store.createEntity({name:'TECH:Extra',entityType:'tech-config'});store.close();const plan=previewRestore(path,directory);await assert.rejects(restoreBackup(path,directory,{confirmation:JSON.stringify(plan),postSwap(){throw new Error('injected');}}),/injected/);let db=new DatabaseSync(path,{readOnly:true});assert.equal(db.prepare('SELECT count(*) AS n FROM entities').get().n,2);db.close();await restoreBackup(path,directory,{confirmation:JSON.stringify(plan)});db=new DatabaseSync(path,{readOnly:true});assert.equal(db.prepare('SELECT count(*) AS n FROM entities').get().n,1);db.close();writeFileSync(join(directory,'brain.db'),'corrupt');assert.throws(()=>verifyBackup(directory),{code:'HERMIT_BACKUP_INVALID'});});
test('reset requires exact preview and verified backup, preserves diagnostics',async t=>{const {root,path}=fixture(t);const options={dataRoot:root,dbPath:path,scope:'knowledge'};const plan=previewReset(options);assert.equal(plan.tables.find(t=>t.name==='entities').rows,1);await assert.rejects(applyReset(options),{code:'HERMIT_CONFIRMATION_REQUIRED'});const result=await applyReset({...options,confirmation:JSON.stringify(plan)});assert.equal(verifyBackup(result.backup.directory).integrity,'ok');const db=new DatabaseSync(path,{readOnly:true});assert.equal(db.prepare('SELECT count(*) AS n FROM entities').get().n,0);db.close();});
test('upgrade uses replacement only and failure leaves original unchanged',async t=>{const {root,path}=fixture(t);const db=new DatabaseSync(path);db.exec('DROP TABLE IF EXISTS schema_meta');db.close();const before=readFileSync(path);const plan=upgradePlan(path);await assert.rejects(applyUpgrade(path,{confirmation:JSON.stringify(plan),migrate(){throw new Error('migration failed');}}),/migration failed/);assert.deepEqual(readFileSync(path),before);await applyUpgrade(path,{confirmation:JSON.stringify(plan),migrate(db){db.exec('CREATE TABLE upgraded(value TEXT)');}});assert.equal(verifyUpgrade(path).revision,3);});
test('junction targets and changed reset previews are rejected',async t=>{const {root,path}=fixture(t);const outside=mkdtempSync(join(tmpdir(),'hermit-outside-'));t.after(()=>rmSync(outside,{recursive:true,force:true}));symlinkSync(outside,join(root,'models'),'junction');assert.throws(()=>previewReset({dataRoot:root,dbPath:path,scope:'models'}),{code:'HERMIT_UNSAFE_PATH'});const options={dataRoot:root,dbPath:path,scope:'knowledge'};const plan=previewReset(options);const store=new BrainStore({dbPath:path});store.createEntity({name:'TECH:New',entityType:'tech-config'});store.close();await assert.rejects(applyReset({...options,confirmation:JSON.stringify(plan)}),{code:'HERMIT_CONFIRMATION_REQUIRED'});});
test('killed maintenance during post-swap recovers original using durable journal',async t=>{const {root,path}=fixture(t);const directory=join(root,'crash-backup');await createBackup(path,directory);const store=new BrainStore({dbPath:path});store.createEntity({name:'TECH:OriginalExtra',entityType:'tech-config'});store.close();const moduleUrl=new URL('../scripts/lib/maintenance/backup-service.mjs',import.meta.url).href;const child=spawn(process.execPath,['--input-type=module','-e',`import {previewRestore,restoreBackup} from ${JSON.stringify(moduleUrl)};const plan=previewRestore(${JSON.stringify(path)},${JSON.stringify(directory)});await restoreBackup(${JSON.stringify(path)},${JSON.stringify(directory)},{confirmation:JSON.stringify(plan),postSwap(){process.exit(77);}});`],{stdio:['ignore','pipe','pipe'],windowsHide:true});assert.equal((await once(child,'exit'))[0],77);assert.throws(()=>acquireRuntimeLease(path),{code:'HERMIT_MAINTENANCE_ACTIVE'});recoverMaintenanceLock(path);const db=new DatabaseSync(path,{readOnly:true});assert.equal(db.prepare('SELECT count(*) AS n FROM entities').get().n,2);db.close();});
test('all reset backs up and retains model and cache payloads',async t=>{const {root,path}=fixture(t);mkdirSync(join(root,'models'));writeFileSync(join(root,'models','model.bin'),'retained');const options={dataRoot:root,dbPath:path,scope:'all'};const plan=previewReset(options);const result=await applyReset({...options,confirmation:JSON.stringify(plan)});assert.equal(existsSync(join(root,'models')),false);assert.equal(readFileSync(join(result.retained[0].retained,'model.bin'),'utf8'),'retained');assert.equal(verifyBackup(result.backup.directory).integrity,'ok');});
test('CLI backup, status and strict option parsing use isolated data root',t=>{const {root}=fixture(t);const run=args=>spawnSync(process.execPath,['scripts/maintenance-cli.mjs',...args],{encoding:'utf8',env:{...process.env,HERMIT_DATA_DIR:root},windowsHide:true});const created=run(['backup','create',join(root,'cli-backup')]);assert.equal(created.status,0,created.stderr);assert.equal(run(['backup','verify',join(root,'cli-backup')]).status,0);assert.equal(run(['maintenance','status']).status,0);assert.equal(run(['backup','restore','--confirm-file']).status,1);assert.equal(run(['reset','all','--force']).status,1);const preview=run(['reset','knowledge','--preview']);assert.equal(preview.status,0,preview.stderr);const file=join(root,'confirmed.json');writeFileSync(file,preview.stdout);const applied=run(['reset','knowledge','--apply','--confirm-file',file]);assert.equal(applied.status,0,applied.stderr);});

test('diagnostics reset reseeds its schema marker and remains writable',async t=>{const {root,path}=fixture(t);const {DiagnosticsStore}=await import('../scripts/lib/diagnostics/store.mjs');let d=new DiagnosticsStore({dbPath:path});d.record({code:'HERMIT_TEST_FAILURE'});d.close();const options={dataRoot:root,dbPath:path,scope:'diagnostics'},plan=previewReset(options);await applyReset({...options,confirmation:JSON.stringify(plan)});d=new DiagnosticsStore({dbPath:path});try{assert.equal(d.summary().failures,0);d.record({code:'HERMIT_TEST_FAILURE'});assert.equal(d.summary().failures,1);}finally{d.close();}});
