import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,readdirSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {spawnSync} from 'node:child_process';
import {BrainStore} from '../scripts/lib/storage/brain-store.mjs';
import {DiagnosticsStore} from '../scripts/lib/diagnostics/store.mjs';
import {importCapsules} from '../scripts/lib/diagnostics/crash-capsule.mjs';
const cli=resolve('scripts/brain-cli.mjs'),launcher=resolve('scripts/hermit-mcp-server.mjs');
function fixture(t){const root=mkdtempSync(join(tmpdir(),'v8-public-')),cwd=join(root,'project'),data=join(root,'data');mkdirSync(cwd);t.after(()=>rmSync(root,{recursive:true,force:true}));const env={...process.env,HERMIT_DATA_DIR:data,HERMIT_DB_PATH:'',HERMIT_STORAGE:'v8',HERMIT_USER_CWD:cwd};return {cwd,data,env,run:args=>spawnSync(process.execPath,[cli,...args],{cwd,env,encoding:'utf8',timeout:30000})};}
test('public diagnostics and index commands execute through packaged entrypoints',t=>{const f=fixture(t);const brain=new BrainStore({dbPath:join(f.data,'brain.db')});const project=brain.createProject({name:'fixture',rootPath:f.cwd});const diagnostics=new DiagnosticsStore({brainStore:brain});diagnostics.record({code:'HERMIT_TEST_FAILURE',component:'cli'},{projectId:project.id});diagnostics.close();brain.close();let r=f.run(['doctor','errors']);assert.equal(r.status,0,r.stderr);assert.match(r.stdout,/HERMIT_TEST_FAILURE/);r=f.run(['doctor','--unknown']);assert.equal(r.status,1);writeFileSync(join(f.cwd,'app.js'),'export function example(){return 1;}');r=f.run(['index']);assert.equal(r.status,0,r.stderr);const cache=JSON.parse(r.stdout).cache;assert.ok(cache.startsWith(join(f.data,'code-cache')));r=f.run(['check-edit','app.js','--format=json']);assert.equal(r.status,0,r.stderr);assert.equal(JSON.parse(r.stdout).files[0].totalSymbols,1);writeFileSync(join(f.cwd,'app.js'),'export function example(){return 1;} export function added(){return 2;}');r=f.run(['check-edit','app.js','--format=json']);assert.equal(r.status,0,r.stderr);assert.equal(JSON.parse(r.stdout).files[0].totalSymbols,2);});
test('launcher startup failure persists safe capsule and imports it exactly once',t=>{const f=fixture(t);const r=spawnSync(process.execPath,[launcher],{cwd:f.cwd,env:{...f.env,HERMIT_STORAGE:'legacy-secret-test'},encoding:'utf8',timeout:10000});assert.equal(r.status,1);assert.doesNotMatch(r.stderr,/legacy-secret-test/);const envelope=r.stderr.split('\n').filter(Boolean).map(line=>{try{return JSON.parse(line);}catch{return null;}}).find(Boolean);assert.equal(envelope.error.code,'HERMIT_LEGACY_RUNTIME_REQUIRED');assert.equal(envelope.error.diagnosticsDegraded,false);const spool=join(f.data,'crash-spool');assert.equal(readdirSync(spool).length,1);assert.doesNotMatch(readFileSync(join(spool,readdirSync(spool)[0]),'utf8'),/legacy-secret-test/);const brain=new BrainStore({dbPath:join(f.data,'brain.db')}),diagnostics=new DiagnosticsStore({brainStore:brain});try{assert.equal(importCapsules({directory:spool,store:diagnostics}).imported,1);assert.equal(importCapsules({directory:spool,store:diagnostics}).imported,0);}finally{diagnostics.close();brain.close();}});
