import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,readdirSync,readFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {spawnSync} from 'node:child_process';
import {BrainStore} from '../scripts/lib/storage/brain-store.mjs';
import {DiagnosticsStore} from '../scripts/lib/diagnostics/store.mjs';
import {importCapsules} from '../scripts/lib/diagnostics/crash-capsule.mjs';
function fixture(t){const root=mkdtempSync(join(tmpdir(),'hermit-process-')),cwd=join(root,'project'),data=join(root,'data');mkdirSync(cwd);const brain=new BrainStore({dbPath:join(data,'brain.db')}),project=brain.createProject({name:'Fixture',rootPath:cwd});brain.close();t.after(()=>rmSync(root,{recursive:true,force:true}));return {root,cwd,data,project,env:{...process.env,HERMIT_DATA_DIR:data,HERMIT_DB_PATH:'',HERMIT_USER_CWD:cwd,HERMIT_STORAGE:'v8',HERMIT_DIAGNOSTICS:'errors',HERMIT_DIAGNOSTIC_CONTEXT:''}};}
const capsules=f=>readdirSync(join(f.data,'crash-spool')).filter(n=>n.endsWith('.json')).map(n=>JSON.parse(readFileSync(join(f.data,'crash-spool',n),'utf8')));
test('real adapter parse failure reports a durable reference without blocking recall',t=>{const f=fixture(t);const r=spawnSync(process.execPath,[resolve('catalog/hooks/kg-auto-recall-codex.cjs')],{cwd:f.cwd,env:f.env,input:'SENTINEL_PRIVATE_INVALID_JSON',encoding:'utf8'});assert.equal(r.status,0);assert.ok(!r.stderr.includes('SENTINEL_PRIVATE_INVALID_JSON'));const c=capsules(f)[0];assert.equal(JSON.parse(r.stderr.trim()).error.correlationId,c.context.operationId);});
test('forked CLI failure keeps parent trace, project scope and queryable capsule',t=>{const f=fixture(t);const r=spawnSync(process.execPath,[resolve('scripts/brain-cli.mjs'),'review','accept','missing'],{cwd:f.cwd,env:f.env,encoding:'utf8'});assert.equal(r.status,1);const c=capsules(f)[0];assert.equal(c.context.projectId,f.project.id);assert.match(c.context.traceId,/^[a-f0-9-]{14}7/);assert.ok(c.context.parentOperationId);assert.notEqual(c.context.parentOperationId,c.context.operationId);assert.match(r.stderr,new RegExp(c.context.operationId));const brain=new BrainStore({dbPath:join(f.data,'brain.db')}),store=new DiagnosticsStore({brainStore:brain});try{importCapsules({directory:join(f.data,'crash-spool'),store});assert.ok(store.show(c.context.operationId,{projectId:f.project.id}));assert.equal(store.show(c.context.operationId),null);}finally{store.close();brain.close();}});
test('hook bridge failures retain stable session and correlation without saving raw upstream ID',t=>{const f=fixture(t);const hook=resolve('scripts/hermit-hook.mjs');const run=payload=>spawnSync(process.execPath,[hook],{env:f.env,encoding:'utf8',input:JSON.stringify({cwd:f.cwd,agent:'codex',upstreamSessionId:'SENTINEL_PRIVATE_SESSION',...payload})});const start=run({op:'session-start'});assert.equal(start.status,0,start.stderr);const session=JSON.parse(start.stdout);const failed=run({op:'capture',entities:'invalid'});assert.equal(failed.status,1);const c=capsules(f)[0];assert.equal(c.context.sessionId,session.sessionId);assert.equal(c.context.projectId,f.project.id);assert.ok(!JSON.stringify(c).includes('SENTINEL_PRIVATE_SESSION'));const before=readFileSync(join(f.data,'brain.db'));assert.equal(run({op:'graph'}).status,0);assert.deepEqual(readFileSync(join(f.data,'brain.db')),before);});
test('CJS bridge returns the child reference rather than discarding stderr',t=>{const f=fixture(t),bridge=resolve('catalog/hooks/lib/sqlite-bridge.cjs');const source=`const {invoke}=require(${JSON.stringify(bridge)});try{invoke({op:'capture',cwd:process.cwd(),entities:'invalid'});}catch(e){console.log(JSON.stringify({correlationId:e.correlationId,degraded:e.diagnosticsDegraded}));}`;const r=spawnSync(process.execPath,['-e',source],{cwd:f.cwd,env:f.env,encoding:'utf8'});assert.equal(r.status,0,r.stderr);const c=capsules(f)[0];assert.equal(JSON.parse(r.stdout).correlationId,c.context.operationId);assert.ok(c.context.parentOperationId);});
