import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,writeFileSync,readdirSync,readFileSync,statSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';import {randomUUID} from 'node:crypto';
import {BrainStore} from '../scripts/lib/storage/brain-store.mjs';import {DiagnosticsStore} from '../scripts/lib/diagnostics/store.mjs';import {pruneDiagnostics} from '../scripts/lib/diagnostics/retention.mjs';import {writeCapsule,importCapsules} from '../scripts/lib/diagnostics/crash-capsule.mjs';import {diagnosticBundle} from '../scripts/lib/diagnostics/bundle.mjs';
function fixture(t,limits={}){const root=mkdtempSync(join(tmpdir(),'hermit-retention-')),brain=new BrainStore({dbPath:join(root,'brain.db')}),store=new DiagnosticsStore({brainStore:brain,limits});t.after(()=>{store.close();brain.close();rmSync(root,{recursive:true,force:true});});return {root,brain,store};}
test('age and count matrix preserves open/linked evidence and lifetime totals',t=>{const {store,brain,root}=fixture(t);const now=Date.now(),old=now-400*86400000;
 const active=store.record({operation:'active'},{operationId:randomUUID()},randomUUID()).id;
 const disposable=store.record({operation:'disposable'},{operationId:randomUUID()}).id;store.transition(disposable,'IGNORED');
 const linked=store.record({operation:'linked'},{operationId:randomUUID()}).id;store.transition(linked,'IGNORED');const entity=brain.createEntity({name:'INCIDENT:Fixture:Protected',entityType:'incident-bug'}).entity;store.db.prepare('UPDATE diag_fingerprint SET incident_entity_id=? WHERE id=?').run(entity.id,linked);
 for(let i=0;i<3;i++)store.session(randomUUID(),i>0);
 for(const table of ['diag_occurrence','diag_operation','diag_transition','diag_import'])store.db.prepare('UPDATE '+table+' SET created_at=?').run(old);
 store.db.prepare('UPDATE diag_session SET heartbeat_at=?').run(old);store.db.prepare('UPDATE diag_fingerprint SET last_seen=?').run(old);store.db.prepare('UPDATE diag_bucket SET day=?').run(Math.floor(old/86400000));
 const totals=store.summary(),before=readFileSync(join(root,'brain.db-wal'));const preview=pruneDiagnostics(store,{dryRun:true,now});assert.equal(preview.apply,false);assert.deepEqual(readFileSync(join(root,'brain.db-wal')),before);
 const result=pruneDiagnostics(store,{now,occurrenceLimit:0,operationLimit:0,sessionLimit:0,fingerprintLimit:0,bucketLimit:0,transitionLimit:0});assert.equal(result.protectedOverBudget,true);
 for(const table of ['diag_occurrence','diag_operation','diag_session','diag_bucket'])assert.equal(store.count(table),0,table);
 assert.ok(store.show(active));assert.ok(store.show(linked));assert.equal(store.show(disposable),null);assert.equal(store.count('diag_transition'),1);assert.equal(store.count('diag_import'),1);assert.equal(store.count('diag_secret'),1);assert.equal(store.faultSalt().length,32);assert.equal(store.summary().failures,totals.failures);assert.equal(store.summary().successes,totals.successes);assert.deepEqual(store.db.prepare('PRAGMA foreign_key_check').all(),[]);
});
test('every diagnostic insertion budget saturates without unbounded row growth or replay',t=>{const {store}=fixture(t,{fingerprints:2,occurrences:2,operations:2,transitions:2,sessions:2,imports:2,buckets:2,totals:2});
 const id1=randomUUID(),id2=randomUUID();store.record({operation:'one'},{operationId:randomUUID()},id1);store.record({operation:'two'},{operationId:randomUUID()},id2);assert.throws(()=>store.record({}, {},randomUUID()),{code:'HERMIT_DIAGNOSTICS_UNAVAILABLE'});assert.equal(store.record({operation:'one'},{},id1).duplicate,true);
 const rows=store.list();for(const row of rows){store.transition(row.id,'ACKNOWLEDGED');store.transition(row.id,'INVESTIGATING');store.transition(row.id,'FIXED_PENDING_VERIFY');}
 store.session(randomUUID());store.session(randomUUID());assert.throws(()=>store.session(randomUUID()));
 for(let i=0;i<20;i++){store.record({operation:'more',message:'SENTINEL_PRIVATE_RETENTION',frames:['scripts/'+ 'x'.repeat(300)],signature:'x'.repeat(1000)},{operationId:randomUUID()});store.success({component:i%2?'cli':'hook'},{projectId:randomUUID()});}
 for(const table of ['diag_fingerprint','diag_occurrence','diag_operation','diag_transition','diag_session','diag_import','diag_bucket','diag_total'])assert.ok(store.count(table)<=2,table);
 assert.equal(store.summary().failures,22);assert.ok(store.summary().dropped>0);assert.ok(!JSON.stringify(diagnosticBundle(store,{samples:true})).includes('SENTINEL_PRIVATE_RETENTION'));
});
test('capsule byte/count limits and corrupt quarantine never preserve raw payloads',t=>{const {root,store}=fixture(t),directory=join(root,'spool');const first=writeCapsule({directory,metadata:{message:'SENTINEL_PRIVATE_RETENTION',frames:['scripts/'+ 'x'.repeat(10000)]},maxCount:1});assert.equal(first.durable,true);assert.ok(statSync(first.path).size<16384);assert.equal(writeCapsule({directory,maxCount:1}).durable,false);assert.equal(writeCapsule({directory,maxBytes:16384}).durable,false);writeFileSync(first.path,'SENTINEL_PRIVATE_RETENTION');const result=importCapsules({directory,store});assert.equal(result.quarantined,1);for(const name of readdirSync(directory))assert.ok(!readFileSync(join(directory,name),'utf8').includes('SENTINEL_PRIVATE_RETENTION'));assert.equal(store.summary().failures,0);
});
