import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,mkdirSync,writeFileSync,existsSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {BrainStore} from '../scripts/lib/storage/brain-store.mjs';import {learnProject} from '../scripts/lib/project-learner.mjs';import {phaseZero} from '../scripts/lib/deep-scan-collector.mjs';
test('scanner writes scoped candidates transactionally without JSONL and deduplicates',async()=>{const root=mkdtempSync(join(tmpdir(),'v8-scan-'));const cwd=join(root,'project');mkdirSync(cwd);writeFileSync(join(cwd,'package.json'),JSON.stringify({name:'sample',type:'module'}));const store=new BrainStore({dbPath:join(root,'brain.db')});try{const result=await learnProject(cwd,{store,silent:true});assert.equal(result.entities,2);const p=store.listProjects()[0];assert.equal(store.listEntities({projectId:p.id}).length,0);assert.equal(store.listEntities({projectId:p.id,lifecycles:['candidate']}).length,2);assert.equal((await learnProject(cwd,{store,silent:true})).observations,0);assert.equal(existsSync(join(cwd,'data','brain.jsonl')),false);assert.equal(phaseZero(cwd,{store}).scanType,'full');await assert.rejects(learnProject(cwd,join(root,'old.jsonl')),/options|legacy|path/i);}finally{store.close();}});
test('scan metadata is scoped and reads hydrated SQLite observations',()=>{const root=mkdtempSync(join(tmpdir(),'v8-meta-'));writeFileSync(join(root,'package.json'),JSON.stringify({name:'sample'}));const store=new BrainStore({dbPath:join(root,'brain.db')});try{store.createEntity({name:'TECH:Sample:ScanMeta',entityType:'tech-config',observations:['LAST_SCAN: 2026-09-08']});assert.equal(phaseZero(root,{store}).scanType,'full');assert.throws(()=>phaseZero(root,join(root,'old.jsonl')),/options|legacy|path/i);}finally{store.close();}});

test('scanner preserves reviewed knowledge and uses scoped active metadata',async()=>{
 const root=mkdtempSync(join(tmpdir(),'v8-reviewed-'));writeFileSync(join(root,'package.json'),JSON.stringify({name:'sample',description:'new inferred description'}));const store=new BrainStore({dbPath:join(root,'brain.db')});
 try{const project=store.createProject({rootPath:root,name:'sample'});const reviewed=store.createEntity({projectId:project.id,name:'BIZ:Sample',entityType:'biz-domain',observations:['WHAT: reviewed description']}).entity;
 await learnProject(root,{store,silent:true});assert.deepEqual(store.getEntity({id:reviewed.id}).observations.map(o=>o.content),['WHAT: reviewed description']);
 store.createEntity({projectId:project.id,name:'TECH:Sample:ScanMeta',entityType:'tech-config',observations:['LAST_SCAN: 2026-09-08']});assert.equal(phaseZero(root,{store}).scanType,'no-changes');
 }finally{store.close();}
});
