import {MemoryService} from '../scripts/lib/memory-service.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,rmSync,existsSync,renameSync,writeFileSync,realpathSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {execFileSync} from 'node:child_process';
import {BrainStore} from '../scripts/lib/storage/brain-store.mjs';
const {resolvePaths}=await import('../scripts/lib/storage/paths.mjs').catch(()=>({}));
const {resolveProject}=await import('../scripts/lib/storage/project-resolver.mjs').catch(()=>({}));
test('data paths ignore cwd and reject relative root overrides',()=>{assert.equal(typeof resolvePaths,'function');assert.throws(()=>resolvePaths({env:{HERMIT_DATA_DIR:'relative'}}));const paths=resolvePaths({env:{HERMIT_DATA_DIR:tmpdir()}});assert.equal(paths.dbPath,join(tmpdir(),'brain.db'));});
test('project resolver finds registered git root from nested directory without creating on reads',()=>{assert.equal(typeof resolveProject,'function');const dir=mkdtempSync(join(tmpdir(),'v8-path-'));let s;try{execFileSync('git',['init',dir],{stdio:'ignore'});mkdirSync(join(dir,'nested'));s=new BrainStore({dbPath:join(dir,'data','brain.db')});assert.equal(resolveProject(s,{rootPath:join(dir,'nested')}),null);const p=resolveProject(s,{rootPath:dir,create:true});assert.equal(resolveProject(s,{rootPath:join(dir,'nested')}).id,p.id);assert.throws(()=>resolveProject(s,{rootPath:dir,projectId:'missing'}),{code:'HERMIT_PROJECT_ID_CONFLICT'});}finally{s?.close();rmSync(dir,{recursive:true,force:true});}});
test('non-git project marker preserves UUID after move and rejects conflicting explicit ID',()=>{const dir=mkdtempSync(join(tmpdir(),'v8-move-'));let s;try{const a=join(dir,'a'),b=join(dir,'b');mkdirSync(a);s=new BrainStore({dbPath:join(dir,'brain.db')});const p=resolveProject(s,{rootPath:a,create:true});assert.equal(existsSync(join(a,'.hermit','project-id')),true);renameSync(a,b);assert.equal(resolveProject(s,{rootPath:b}).id,p.id);const other=s.createProject({name:'other',rootPath:dir});assert.throws(()=>resolveProject(s,{rootPath:b,projectId:other.id}),{code:'HERMIT_PROJECT_ID_CONFLICT'});}finally{s?.close();rmSync(dir,{recursive:true,force:true});}});
test('git worktrees share common-directory identity and reads never create markers',()=>{const dir=mkdtempSync(join(tmpdir(),'v8-worktree-'));let s;try{const repo=join(dir,'repo'),work=join(dir,'work');mkdirSync(repo);execFileSync('git',['init',repo],{stdio:'ignore'});execFileSync('git',['-C',repo,'-c','user.name=Test','-c','user.email=test@example.com','commit','--allow-empty','-m','init'],{stdio:'ignore'});execFileSync('git',['-C',repo,'worktree','add','-b','second',work],{stdio:'ignore'});s=new BrainStore({dbPath:join(dir,'brain.db')});assert.equal(resolveProject(s,{rootPath:repo}),null);assert.equal(existsSync(join(repo,'.git','hermit-project-id')),false);const p=resolveProject(s,{rootPath:repo,create:true});assert.equal(resolveProject(s,{rootPath:work}).id,p.id);}finally{s?.close();rmSync(dir,{recursive:true,force:true});}});

test('marker cannot override an existing path identity',()=>{const dir=mkdtempSync(join(tmpdir(),'v8-conflict-'));let s;try{const a=join(dir,'a'),b=join(dir,'b');mkdirSync(a);mkdirSync(b);s=new BrainStore({dbPath:join(dir,'brain.db')});const first=resolveProject(s,{rootPath:a,create:true}),second=resolveProject(s,{rootPath:b,create:true});writeFileSync(join(a,'.hermit','project-id'),second.id);assert.throws(()=>resolveProject(s,{rootPath:a,create:true}),{code:'HERMIT_PROJECT_ID_CONFLICT'});assert.equal(s.resolveProjectAlias({aliasType:'path',aliasValue:process.platform==='win32'?a.toLowerCase():a}).id,first.id);}finally{s?.close();rmSync(dir,{recursive:true,force:true});}});

test('session execution root follows moves and worktrees without changing shared identity',()=>{const dir=mkdtempSync(join(tmpdir(),'v8-session-root-'));let s;try{const repo=join(dir,'repo'),work=join(dir,'work');mkdirSync(repo);execFileSync('git',['init',repo],{stdio:'ignore'});execFileSync('git',['-C',repo,'-c','user.name=Test','-c','user.email=test@example.com','commit','--allow-empty','-m','init'],{stdio:'ignore'});execFileSync('git',['-C',repo,'worktree','add','-b','second',work],{stdio:'ignore'});s=new BrainStore({dbPath:join(dir,'brain.db')});const service=new MemoryService({store:s});const p=service.startSession(repo);assert.equal(realpathSync.native(service.sessionRootPath),realpathSync.native(repo));assert.equal(service.startSession(work).id,p.id);assert.equal(realpathSync.native(service.sessionRootPath),realpathSync.native(work));assert.throws(()=>service.startSession(join(dir,'missing')));assert.equal(realpathSync.native(service.sessionRootPath),realpathSync.native(work));assert.equal(service.projectId,p.id);const a=join(dir,'a'),b=join(dir,'b');mkdirSync(a);const moved=service.startSession(a);renameSync(a,b);assert.equal(service.startSession(b).id,moved.id);assert.equal(realpathSync.native(service.sessionRootPath),realpathSync.native(b));}finally{s?.close();rmSync(dir,{recursive:true,force:true});}});
