import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
const module = await import('../scripts/lib/storage/brain-store.mjs').catch(() => ({}));
const { BrainStore } = module;
function fixture(t) { const dir=mkdtempSync(join(tmpdir(),'hermit-v8-')); process.once('exit',()=>rmSync(dir,{recursive:true,force:true})); return join(dir,'brain.db'); }
test('store durably scopes same names, deduplicates observations and searches across observations',t=>{
 assert.equal(typeof BrainStore,'function'); const dbPath=fixture(t); let s=new BrainStore({dbPath});
 const p=s.createProject({name:'one',rootPath:tmpdir()});
 const a=s.createEntity({name:'TECH:Shared',entityType:'tech-stack',observations:['FRONTEND: alpha','BACKEND: omega'],projectId:p.id}).entity;
 const b=s.createEntity({name:'TECH:Shared',entityType:'tech-stack',observations:['global']}).entity;
 assert.notEqual(a.id,b.id); assert.equal(s.createEntity({name:a.name,entityType:a.entityType,projectId:p.id,observations:['FRONTEND: alpha']}).idempotent,true);
 assert.equal(s.getEntity({id:a.id}).observations.length,2); assert.equal(s.search('alpha omega',{projectId:p.id})[0].id,a.id); assert.equal(s.search('alpha omega').length,0);
 s.close(); s=new BrainStore({dbPath}); assert.equal(s.getEntity({id:a.id}).observations[0].content,'FRONTEND: alpha'); s.close();
});
test('failed nested batch rolls back graph and search together',t=>{ assert.equal(typeof BrainStore,'function'); const s=new BrainStore({dbPath:fixture(t)}); t.after(()=>s.close()); assert.throws(()=>s.batch(()=>{s.createEntity({name:'TECH:Rollback',entityType:'tech-stack',observations:['needle']}); s.createEntity({name:'invalid',entityType:'bad',observations:[]});})); assert.equal(s.listEntities().length,0); assert.equal(s.search('needle').length,0); });
test('candidate and archived content excluded; lifecycle preserves history and relation visibility',t=>{ assert.equal(typeof BrainStore,'function');const s=new BrainStore({dbPath:fixture(t)});t.after(()=>s.close());const a=s.createEntity({name:'TECH:A',entityType:'tech-stack',observations:['needle'],lifecycle:'candidate'}).entity; assert.equal(s.search('needle').length,0);s.transitionEntity({id:a.id,to:'active',actor:'test',reason:'verified'});const b=s.createEntity({name:'TECH:B',entityType:'tech-stack',observations:[]}).entity;s.createRelation({fromEntityId:a.id,toEntityId:b.id,relationType:'depends_on'});s.transitionEntity({id:a.id,to:'archived'});assert.equal(s.listRelations().length,0);assert.equal(s.search('needle').length,0);s.transitionEntity({id:a.id,to:'active'});assert.equal(s.listRelations().length,1);assert.equal(s.search('needle').length,1);assert.equal(s.listChangeEvents({entityId:a.id}).filter(e=>e.action==='transition').length,3);});
test('opening a legacy database refuses without rewriting its bytes',t=>{assert.equal(typeof BrainStore,'function');const dbPath=fixture(t);const db=new DatabaseSync(dbPath);db.exec('CREATE TABLE legacy(value TEXT); PRAGMA user_version=7');db.close();const before=readFileSync(dbPath);assert.throws(()=>new BrainStore({dbPath}),{code:'HERMIT_UPGRADE_REQUIRED'});assert.deepEqual(readFileSync(dbPath),before);});

test('diagnostics persist only allowlisted metadata, isolate project scope, resolve and prune',t=>{const s=new BrainStore({dbPath:fixture(t)});t.after(()=>s.close());assert.equal(typeof s.recordDiagnostic,'function');const p=s.createProject({name:'diag',rootPath:tmpdir()});const d=s.recordDiagnostic({projectId:p.id,code:'HERMIT_TEST',component:'search',message:'password=secret-sentinel',args:{token:'secret-sentinel'}});assert.equal(s.listDiagnostics().length,0);assert.equal(s.listDiagnostics({projectId:p.id})[0].id,d.id);assert.equal(JSON.stringify(s.listDiagnostics({projectId:p.id})).includes('secret-sentinel'),false);s.resolveDiagnostic({id:d.id,projectId:p.id});assert.equal(s.listDiagnostics({projectId:p.id,status:'resolved'}).length,1);s.pruneDiagnostics({before:new Date(Date.now()+1000).toISOString()});assert.equal(s.listDiagnostics({projectId:p.id,status:'resolved'}).length,0);});
test('consistent backup opens read-only with original graph',async t=>{const dbPath=fixture(t);const s=new BrainStore({dbPath});t.after(()=>s.close());const e=s.createEntity({name:'TECH:Backup',entityType:'tech-stack',observations:['durable']}).entity;await s.backup(dbPath+'.backup');const copy=new BrainStore({dbPath:dbPath+'.backup',readOnly:true});try{assert.equal(copy.integrityCheck(),true);assert.equal(copy.getEntity({id:e.id}).name,'TECH:Backup');assert.throws(()=>copy.createEntity({name:'TECH:No',entityType:'tech-stack'}));}finally{copy.close();}});
test('archived search is explicit and candidates remain hidden',t=>{const s=new BrainStore({dbPath:fixture(t)});t.after(()=>s.close());const a=s.createEntity({name:'TECH:Archived',entityType:'tech-stack',observations:['archivedneedle']}).entity;s.transitionEntity({id:a.id,to:'archived'});s.createEntity({name:'TECH:Candidate',entityType:'tech-stack',observations:['archivedneedle'],lifecycle:'candidate'});assert.equal(s.search('archivedneedle',{includeArchived:true})[0]?.id,a.id);assert.equal(s.search('archivedneedle',{includeArchived:true}).length,1);});
test('observation archive and restore update lexical content atomically',t=>{const s=new BrainStore({dbPath:fixture(t)});t.after(()=>s.close());const a=s.createEntity({name:'TECH:Observation',entityType:'tech-stack',observations:['needle']}).entity;s.transitionObservation({id:a.observations[0].id,to:'archived'});assert.equal(s.search('needle').length,0);s.transitionObservation({id:a.observations[0].id,to:'active'});assert.equal(s.search('needle').length,1);});
