// Metadata-only by construction. Never inspect error messages, stacks, arguments or results.
const components=new Set('runtime search storage model setup hook mcp cli scan diagnostics code-index bridge'.split(' '));
const phases=new Set('startup import open initialize ready request background shutdown rollback'.split(' '));
const categories=new Set(['internal','expected','dependency','timeout','cancelled']);
const codes=new Set('HERMIT_RUNTIME_ERROR HERMIT_TOOL_ERROR HERMIT_TIMEOUT HERMIT_BOOT_FAILURE HERMIT_TEST_FAILURE HERMIT_VALIDATION HERMIT_SCHEMA_UNSUPPORTED HERMIT_MODEL_UNAVAILABLE HERMIT_INDEX_STALE HERMIT_STORAGE_BUSY HERMIT_NOT_FOUND HERMIT_SESSION_REQUIRED HERMIT_SCOPE_REQUIRED HERMIT_ENTITY_CONFLICT HERMIT_INVALID_TRANSITION HERMIT_ASYNC_TRANSACTION HERMIT_PROJECT_CONFLICT HERMIT_SETUP_CONFLICT HERMIT_BACKUP_INVALID HERMIT_DIAGNOSTICS_UNAVAILABLE HERMIT_CANCELLED HERMIT_DEPENDENCY_ERROR'.split(' '));
for(const code of ['HERMIT_UPGRADE_REQUIRED','HERMIT_RUNTIME_TOO_OLD','HERMIT_NODE_UNSUPPORTED','HERMIT_LEGACY_RUNTIME_REQUIRED','HERMIT_STORE_MISSING','HERMIT_MAINTENANCE_ACTIVE','HERMIT_SCAN_STALE','HERMIT_SCAN_CONFLICT'])codes.add(code);
for(const code of ["HERMIT_SCHEMA_UNSUPPORTED","HERMIT_BACKUP_INVALID","HERMIT_BACKUP_EXISTS","HERMIT_RUNTIME_ACTIVE","HERMIT_UNSAFE_PATH","HERMIT_CONFIRMATION_REQUIRED","HERMIT_UNOWNED_ROOT","HERMIT_MAINTENANCE_REQUIRED","HERMIT_MAINTENANCE_ACTIVE","HERMIT_MIXED_RUNTIME","HERMIT_STALE_PROOF_REQUIRED","HERMIT_RECOVERY_ACTIVE","HERMIT_RECOVERY_INVALID","HERMIT_STALE_LEASE_RECOVERED","HERMIT_VALIDATION","HERMIT_PLAN_STALE","HERMIT_UPGRADE_REQUIRED","HERMIT_UNKNOWN_AGENT","HERMIT_CONFIG_PARSE","HERMIT_LEGACY_CONFIG","HERMIT_CONFIG_CONFLICT","HERMIT_OWNERSHIP_CONFLICT","HERMIT_CONFIG_ENCODING","HERMIT_INVALID_SETUP_MANIFEST","HERMIT_MCP_SMOKE_FAILED","HERMIT_MCP_SMOKE_TIMEOUT","HERMIT_SETUP_ABSOLUTE_PATH_REQUIRED","HERMIT_SERVER_MISSING","HERMIT_UNOWNED_DATA_ROOT","HERMIT_UNSAFE_DATA_ROOT","HERMIT_UNSAFE_HOOK_COMMAND_PATH","HERMIT_PLAN_UNTRUSTED","HERMIT_INVALID_SETUP_PLAN","HERMIT_SETUP_VERIFY_FAILED","HERMIT_ROLLBACK_CONFLICT","HERMIT_SETUP_CONFLICT","HERMIT_SETUP_FAILED","HERMIT_MANIFEST_TARGET"])codes.add(code);
export function safeMetadata(input={}) {
 return {code:codes.has(input.code)?input.code:'HERMIT_RUNTIME_ERROR',component:components.has(input.component)?input.component:'runtime',phase:phases.has(input.phase)?input.phase:'request',category:categories.has(input.category)?input.category:'internal',durationMs:Number.isFinite(input.durationMs)?Math.max(0,Math.min(86400000,Math.round(input.durationMs))):0};
}
export function safeErrorEnvelope({code,correlationId,diagnosticsDegraded=false}={}) {return {ok:false,error:{code:safeMetadata({code}).code,message:'Operation failed. Inspect local diagnostics for the reference.',category:'internal',retryable:false,correlationId,diagnosticsDegraded}};}
