// Only safe metadata is persisted. Raw messages/stacks are handled only by the HMAC boundary.
const components=new Set('runtime search storage model setup hook mcp cli scan diagnostics code-index bridge'.split(' '));
const phases=new Set('startup import open initialize ready request background shutdown rollback'.split(' '));
const categories=new Set(['internal','expected','dependency','timeout','cancelled']);
const codes=new Set('HERMIT_RUNTIME_ERROR HERMIT_TOOL_ERROR HERMIT_TIMEOUT HERMIT_BOOT_FAILURE HERMIT_TEST_FAILURE HERMIT_VALIDATION HERMIT_SCHEMA_UNSUPPORTED HERMIT_MODEL_UNAVAILABLE HERMIT_INDEX_STALE HERMIT_STORAGE_BUSY HERMIT_NOT_FOUND HERMIT_SESSION_REQUIRED HERMIT_SCOPE_REQUIRED HERMIT_ENTITY_CONFLICT HERMIT_INVALID_TRANSITION HERMIT_ASYNC_TRANSACTION HERMIT_PROJECT_CONFLICT HERMIT_SETUP_CONFLICT HERMIT_BACKUP_INVALID HERMIT_DIAGNOSTICS_UNAVAILABLE HERMIT_CANCELLED HERMIT_DEPENDENCY_ERROR'.split(' '));
for(const code of ['HERMIT_UPGRADE_REQUIRED','HERMIT_RUNTIME_TOO_OLD','HERMIT_NODE_UNSUPPORTED','HERMIT_LEGACY_RUNTIME_REQUIRED','HERMIT_STORE_MISSING','HERMIT_MAINTENANCE_ACTIVE','HERMIT_SCAN_STALE','HERMIT_SCAN_CONFLICT'])codes.add(code);
for(const code of ["HERMIT_SCHEMA_UNSUPPORTED","HERMIT_BACKUP_INVALID","HERMIT_BACKUP_EXISTS","HERMIT_RUNTIME_ACTIVE","HERMIT_UNSAFE_PATH","HERMIT_CONFIRMATION_REQUIRED","HERMIT_UNOWNED_ROOT","HERMIT_MAINTENANCE_REQUIRED","HERMIT_MAINTENANCE_ACTIVE","HERMIT_MIXED_RUNTIME","HERMIT_STALE_PROOF_REQUIRED","HERMIT_RECOVERY_ACTIVE","HERMIT_RECOVERY_INVALID","HERMIT_STALE_LEASE_RECOVERED","HERMIT_VALIDATION","HERMIT_PLAN_STALE","HERMIT_UPGRADE_REQUIRED","HERMIT_UNKNOWN_AGENT","HERMIT_CONFIG_PARSE","HERMIT_LEGACY_CONFIG","HERMIT_CONFIG_CONFLICT","HERMIT_OWNERSHIP_CONFLICT","HERMIT_CONFIG_ENCODING","HERMIT_INVALID_SETUP_MANIFEST","HERMIT_MCP_SMOKE_FAILED","HERMIT_MCP_SMOKE_TIMEOUT","HERMIT_SETUP_ABSOLUTE_PATH_REQUIRED","HERMIT_SERVER_MISSING","HERMIT_UNOWNED_DATA_ROOT","HERMIT_UNSAFE_DATA_ROOT","HERMIT_UNSAFE_HOOK_COMMAND_PATH","HERMIT_PLAN_UNTRUSTED","HERMIT_INVALID_SETUP_PLAN","HERMIT_SETUP_VERIFY_FAILED","HERMIT_ROLLBACK_CONFLICT","HERMIT_SETUP_CONFLICT","HERMIT_SETUP_FAILED","HERMIT_MANIFEST_TARGET"])codes.add(code);
const expectedCodes=new Set('HERMIT_VALIDATION HERMIT_NOT_FOUND HERMIT_SESSION_REQUIRED HERMIT_SCOPE_REQUIRED HERMIT_ENTITY_CONFLICT HERMIT_INVALID_TRANSITION HERMIT_PROJECT_CONFLICT HERMIT_CONFIG_CONFLICT HERMIT_CONFIRMATION_REQUIRED HERMIT_UPGRADE_REQUIRED HERMIT_BACKUP_EXISTS HERMIT_PLAN_STALE HERMIT_UNKNOWN_AGENT HERMIT_UNOWNED_DATA_ROOT HERMIT_UNOWNED_ROOT HERMIT_RUNTIME_ACTIVE HERMIT_MIXED_RUNTIME'.split(' '));
export function safeMetadata(input={}) {
 const operation=typeof input.operation==='string'&&input.operation.length<=64&&/^(?:hermit_[a-z_]+|[a-z][a-z-]{0,31})$/.test(input.operation)?input.operation:'unknown';
 const errorName=['Error','TypeError','RangeError','SyntaxError','ReferenceError','URIError','EvalError','AggregateError','AbortError'].includes(input.errorName)?input.errorName:'Error';
 const signature=typeof input.signature==='string'&&/^[a-f0-9]{64}$/.test(input.signature)?input.signature:'';
 const frames=Array.isArray(input.frames)?input.frames.filter(f=>typeof f==='string'&&f.length<=200&&/^(?:scripts|catalog)\/[A-Za-z0-9_./-]+(?:#[A-Za-z0-9_$<>.[\] -]+)?$/.test(f)).slice(0,3):[];
 return {operation,errorName,signature,frames,code:codes.has(input.code)?input.code:'HERMIT_RUNTIME_ERROR',component:components.has(input.component)?input.component:'runtime',phase:phases.has(input.phase)?input.phase:'request',category:categories.has(input.category)?input.category:expectedCodes.has(input.code)?'expected':input.code==='HERMIT_TIMEOUT'?'timeout':'internal',durationMs:Number.isFinite(input.durationMs)?Math.max(0,Math.min(86400000,Math.round(input.durationMs))):0};
}
export function safeErrorEnvelope({code,correlationId,diagnosticRef=null,diagnosticsDegraded=false}={}) {return {ok:false,error:{code:safeMetadata({code}).code,message:'Operation failed. Inspect local diagnostics for the reference.',category:safeMetadata({code}).category,retryable:false,correlationId,diagnosticRef,diagnosticsDegraded}};}
