import { DatabaseSync, backup } from 'node:sqlite';
import { randomUUID } from 'node:crypto';
import { mkdirSync, existsSync, realpathSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
const TYPES = new Set(['biz-domain','biz-rule','biz-flow','biz-entity','pattern-code','pattern-arch','pattern-integration','tech-stack','tech-config','tech-person','tech-decision','incident-bug','incident-gotcha']);
const RELATIONS = new Set('has_rule has_flow has_entity uses_tech uses_pattern leads works_on reviews decided used_in extends alternative_to found_in applies_to decided_for depends_on triggers part_of input_to output_of'.split(' '));
const STATES = ['candidate','active','archived','rejected'];
const now = () => new Date().toISOString();
function fail(code,message) { throw Object.assign(new Error(message),{code}); }
function required(v,label) { if(typeof v!=='string'||!v.trim()) fail('HERMIT_VALIDATION',`${label} must be nonempty`); return v.trim(); }
function canonical(p) { let value=realpathSync(resolve(p));return process.platform==='win32'?value.toLowerCase():value; }
export class BrainStore {
 constructor({dbPath,readOnly=false}={}) {
  required(dbPath,'dbPath'); this.dbPath=resolve(dbPath); this.depth=0;
  if(existsSync(this.dbPath)) { const probe=new DatabaseSync(this.dbPath,{readOnly:true}); try { const version=probe.prepare('PRAGMA user_version').get().user_version;const tables=probe.prepare("SELECT name FROM sqlite_master WHERE type='table'").all(); if(version!==8 && (version!==0||tables.length)) fail('HERMIT_SCHEMA_UNSUPPORTED',`Database schema ${version} is not v8; existing database preserved`); } finally {probe.close();} }
  if(!readOnly) mkdirSync(dirname(this.dbPath),{recursive:true});
  this.db=new DatabaseSync(this.dbPath,{readOnly});
  try {this.db.exec('PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;');if(!readOnly){this.db.exec('PRAGMA journal_mode=WAL;');this.initialize();}else if(this.db.prepare('PRAGMA user_version').get().user_version!==8)fail('HERMIT_SCHEMA_UNSUPPORTED','Expected schema v8');}catch(e){this.db.close();throw e;}
 }
 initialize(){this.db.exec(`BEGIN IMMEDIATE;
 CREATE TABLE IF NOT EXISTS projects(id TEXT PRIMARY KEY,name TEXT NOT NULL,root_path TEXT NOT NULL,created_at TEXT NOT NULL) STRICT;
 CREATE TABLE IF NOT EXISTS project_aliases(alias_type TEXT NOT NULL,alias_value TEXT NOT NULL,project_id TEXT NOT NULL REFERENCES projects(id),PRIMARY KEY(alias_type,alias_value)) STRICT;
 CREATE TABLE IF NOT EXISTS entities(id TEXT PRIMARY KEY,name TEXT NOT NULL,entity_type TEXT NOT NULL,project_id TEXT REFERENCES projects(id),lifecycle TEXT NOT NULL CHECK(lifecycle IN ('active','candidate','archived','rejected')),provenance TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL) STRICT;
 CREATE UNIQUE INDEX IF NOT EXISTS entity_scope_name ON entities(COALESCE(project_id,''),name);
 CREATE TABLE IF NOT EXISTS observations(id TEXT PRIMARY KEY,entity_id TEXT NOT NULL REFERENCES entities(id),content TEXT NOT NULL,lifecycle TEXT NOT NULL,provenance TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(entity_id,content)) STRICT;
 CREATE TABLE IF NOT EXISTS relations(id TEXT PRIMARY KEY,from_entity_id TEXT NOT NULL REFERENCES entities(id),to_entity_id TEXT NOT NULL REFERENCES entities(id),relation_type TEXT NOT NULL,lifecycle TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(from_entity_id,to_entity_id,relation_type)) STRICT;
 CREATE TABLE IF NOT EXISTS change_events(id TEXT PRIMARY KEY,entity_id TEXT REFERENCES entities(id),action TEXT NOT NULL,actor TEXT NOT NULL,reason TEXT NOT NULL,created_at TEXT NOT NULL) STRICT;
 CREATE TABLE IF NOT EXISTS diag_events(id TEXT PRIMARY KEY,project_id TEXT REFERENCES projects(id),code TEXT NOT NULL,component TEXT NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL,resolved_at TEXT) STRICT;
 CREATE VIRTUAL TABLE IF NOT EXISTS entity_fts USING fts5(entity_id UNINDEXED,name,content);
 PRAGMA user_version=8; COMMIT;`);}
 close(){this.db.close();}
 batch(fn){const point=`nested_${this.depth++}`;const outer=this.depth===1;this.db.exec(outer?'BEGIN IMMEDIATE':`SAVEPOINT ${point}`);try{const result=fn(this);if(result?.then)fail('HERMIT_ASYNC_TRANSACTION','Transactions must be synchronous');this.db.exec(outer?'COMMIT':`RELEASE ${point}`);return result;}catch(e){this.db.exec(outer?'ROLLBACK':`ROLLBACK TO ${point}; RELEASE ${point}`);throw e;}finally{this.depth--;}}
 createProject({name,rootPath}) {required(name,'name');const path=canonical(rootPath);return this.batch(()=>{const existing=this.resolveProjectAlias({aliasType:'path',aliasValue:path});if(existing)return existing;const id=randomUUID();this.db.prepare('INSERT INTO projects VALUES(?,?,?,?)').run(id,name,path,now());this.db.prepare('INSERT INTO project_aliases VALUES(?,?,?)').run('path',path,id);return this.getProject(id);});}
 resolveProjectAlias({aliasType,aliasValue}){const row=this.db.prepare('SELECT project_id FROM project_aliases WHERE alias_type=? AND alias_value=?').get(aliasType,aliasValue);return row?this.getProject(row.project_id):null;}
 getProject(id){const r=this.db.prepare('SELECT * FROM projects WHERE id=?').get(id);return r?{id:r.id,name:r.name,rootPath:r.root_path,createdAt:r.created_at}:null;}
 listProjects(){return this.db.prepare('SELECT id FROM projects ORDER BY name,id').all().map(r=>this.getProject(r.id));}
 event(id,action,actor='user',reason=''){this.db.prepare('INSERT INTO change_events VALUES(?,?,?,?,?,?)').run(randomUUID(),id,action,actor??'user',reason??'',now());}
 refresh(id){this.db.prepare('DELETE FROM entity_fts WHERE entity_id=?').run(id);const e=this.db.prepare("SELECT * FROM entities WHERE id=? AND lifecycle='active'").get(id);if(e){const text=this.db.prepare("SELECT content FROM observations WHERE entity_id=? AND lifecycle='active' ORDER BY rowid").all(id).map(r=>r.content).join('\n');this.db.prepare('INSERT INTO entity_fts(entity_id,name,content) VALUES(?,?,?)').run(id,e.name,text);}}
 createEntity({name,entityType,observations=[],projectId=null,lifecycle='active',provenance={}}){required(name,'name');if(!TYPES.has(entityType)||!STATES.includes(lifecycle)||!Array.isArray(observations))fail('HERMIT_VALIDATION','Invalid entity type, lifecycle or observations');observations.forEach(o=>required(o,'observation'));return this.batch(()=>{let entity=this.getEntity({name,projectId,lifecycles:STATES});const idempotent=!!entity;if(entity && entity.entityType!==entityType)fail('HERMIT_ENTITY_CONFLICT','Existing entity has another type');if(!entity){const id=randomUUID(),time=now();this.db.prepare('INSERT INTO entities VALUES(?,?,?,?,?,?,?,?)').run(id,name,entityType,projectId,lifecycle,JSON.stringify(provenance),time,time);this.event(id,'create');entity={id};}for(const content of observations)this.addObservation({entityId:entity.id,content,provenance});this.refresh(entity.id);return {entity:this.getEntity({id:entity.id,lifecycles:STATES}),idempotent,warnings:observations.length?[]:['Recommended observations are missing']};});}
 addObservation({entityId,content,provenance={}}){required(content,'content');return this.batch(()=>{if(!this.getEntity({id:entityId,lifecycles:STATES}))fail('HERMIT_NOT_FOUND','Entity not found');const existing=this.db.prepare('SELECT id FROM observations WHERE entity_id=? AND content=?').get(entityId,content);if(existing)return this.observation(existing.id);const id=randomUUID(),time=now();this.db.prepare('INSERT INTO observations VALUES(?,?,?,?,?,?,?)').run(id,entityId,content,'active',JSON.stringify(provenance),time,time);this.db.prepare('UPDATE entities SET updated_at=? WHERE id=?').run(time,entityId);this.event(entityId,'add_observation');this.refresh(entityId);return this.observation(id);});}
 observation(id){const r=this.db.prepare('SELECT * FROM observations WHERE id=?').get(id);return r?{id:r.id,entityId:r.entity_id,content:r.content,lifecycle:r.lifecycle,provenance:JSON.parse(r.provenance),createdAt:r.created_at,updatedAt:r.updated_at}:null;}
 getEntity({id,name,projectId=null,lifecycles=['active']}){const r=id?this.db.prepare('SELECT * FROM entities WHERE id=?').get(id):this.db.prepare('SELECT * FROM entities WHERE name=? AND project_id IS ?').get(name,projectId);if(!r||!lifecycles.includes(r.lifecycle))return null;return {id:r.id,name:r.name,entityType:r.entity_type,projectId:r.project_id,lifecycle:r.lifecycle,provenance:JSON.parse(r.provenance),createdAt:r.created_at,updatedAt:r.updated_at,observations:this.db.prepare("SELECT id FROM observations WHERE entity_id=? AND lifecycle='active' ORDER BY rowid").all(r.id).map(o=>this.observation(o.id))};}
 listEntities({projectId=null,includeGlobal=false,lifecycles=['active']}={}){return this.db.prepare('SELECT id FROM entities WHERE project_id IS ? OR (?=1 AND project_id IS NULL) ORDER BY name,id').all(projectId,Number(includeGlobal)).map(r=>this.getEntity({id:r.id,lifecycles})).filter(Boolean);}
 search(query,{projectId=null,includeGlobal=false,topK=20,includeArchived=false}={}){const tokens=String(query).match(/[\p{L}\p{N}_]+/gu)||[];if(!tokens.length)return [];if(includeArchived){return this.listEntities({projectId,includeGlobal,lifecycles:['active','archived']}).filter(e=>{const terms=(e.name+' '+e.observations.map(o=>o.content).join(' ')).toLowerCase().match(/[\p{L}\p{N}_]+/gu)||[];return tokens.every(t=>terms.includes(t.toLowerCase()));}).slice(0,Math.max(1,Math.min(1000,Number(topK)||20))).map(e=>({...e,score:1}));}const match=tokens.map(t=>'"'+t+'"').join(' AND ');const hits=this.db.prepare('SELECT entity_id,bm25(entity_fts) AS rank FROM entity_fts JOIN entities e ON e.id=entity_fts.entity_id WHERE entity_fts MATCH ? AND (e.project_id IS ? OR (?=1 AND e.project_id IS NULL)) ORDER BY rank,entity_id LIMIT ?').all(match,projectId,Number(includeGlobal),Math.max(1,Math.min(1000,Number(topK)||20)));return hits.map(r=>({...this.getEntity({id:r.entity_id}),score:-r.rank}));}
 createRelation({fromEntityId,toEntityId,relationType}){if(!RELATIONS.has(relationType))fail('HERMIT_VALIDATION','Invalid relation type');return this.batch(()=>{for(const id of [fromEntityId,toEntityId])if(!this.getEntity({id,lifecycles:['active','candidate']}))fail('HERMIT_NOT_FOUND','Relation endpoint not found or inactive');const existing=this.db.prepare('SELECT id FROM relations WHERE from_entity_id=? AND to_entity_id=? AND relation_type=?').get(fromEntityId,toEntityId,relationType);const id=existing?.id??randomUUID();if(!existing)this.db.prepare('INSERT INTO relations VALUES(?,?,?,?,?,?)').run(id,fromEntityId,toEntityId,relationType,'active',now());return this.listRelations({entityId:fromEntityId}).find(r=>r.id===id)??{id,fromEntityId,toEntityId,relationType,lifecycle:'active'};});}
 listRelations({entityId}={}){return this.db.prepare("SELECT r.* FROM relations r JOIN entities a ON a.id=r.from_entity_id JOIN entities b ON b.id=r.to_entity_id WHERE r.lifecycle='active' AND a.lifecycle='active' AND b.lifecycle='active' AND (? IS NULL OR r.from_entity_id=? OR r.to_entity_id=?) ORDER BY r.rowid").all(entityId??null,entityId??null,entityId??null).map(r=>({id:r.id,fromEntityId:r.from_entity_id,toEntityId:r.to_entity_id,relationType:r.relation_type,lifecycle:r.lifecycle,createdAt:r.created_at}));}
 transitionEntity({id,to,actor,reason}){return this.batch(()=>{const e=this.getEntity({id,lifecycles:STATES});if(!e)fail('HERMIT_NOT_FOUND','Entity not found');const allowed={candidate:['active','rejected','archived'],active:['archived'],archived:['active'],rejected:['candidate']};if(e.lifecycle===to)return e;if(!allowed[e.lifecycle].includes(to))fail('HERMIT_INVALID_TRANSITION','Invalid lifecycle transition');this.db.prepare('UPDATE entities SET lifecycle=?,updated_at=? WHERE id=?').run(to,now(),id);this.event(id,'transition',actor,reason);this.refresh(id);return this.getEntity({id,lifecycles:STATES});});}
 transitionObservation({id,to}){if(!['active','archived'].includes(to))fail('HERMIT_INVALID_TRANSITION','Invalid observation lifecycle');return this.batch(()=>{const o=this.observation(id);if(!o)fail('HERMIT_NOT_FOUND','Observation not found');this.db.prepare('UPDATE observations SET lifecycle=?,updated_at=? WHERE id=?').run(to,now(),id);this.event(o.entityId,'observation_transition');this.refresh(o.entityId);return this.observation(id);});}
 listChangeEvents({entityId}){return this.db.prepare('SELECT * FROM change_events WHERE entity_id=? ORDER BY rowid').all(entityId).map(r=>({id:r.id,entityId:r.entity_id,action:r.action,actor:r.actor,reason:r.reason,createdAt:r.created_at}));}
 recordDiagnostic({projectId=null,code='HERMIT_RUNTIME_ERROR',component='runtime'}={}){const safeCode=/^HERMIT_[A-Z0-9_]{1,80}$/.test(code)?code:'HERMIT_RUNTIME_ERROR';const safeComponent=['runtime','search','storage','model','setup','hook','mcp','cli','scan','diagnostics'].includes(component)?component:'runtime';return this.batch(()=>{const id=randomUUID();this.db.prepare('INSERT INTO diag_events VALUES(?,?,?,?,?,?,NULL)').run(id,projectId,safeCode,safeComponent,'open',now());this.db.prepare("DELETE FROM diag_events WHERE id IN (SELECT id FROM diag_events WHERE status='resolved' ORDER BY created_at DESC LIMIT -1 OFFSET 1000)").run();return this.listDiagnostics({projectId}).find(d=>d.id===id);});}
 listDiagnostics({projectId=null,status,limit=100}={}){return this.db.prepare('SELECT * FROM diag_events WHERE project_id IS ? AND (? IS NULL OR status=?) ORDER BY rowid DESC LIMIT ?').all(projectId,status??null,status??null,Math.max(1,Math.min(1000,Number(limit)||100))).map(r=>({id:r.id,projectId:r.project_id,code:r.code,component:r.component,status:r.status,createdAt:r.created_at,resolvedAt:r.resolved_at}));}
 resolveDiagnostic({id,projectId=null}){this.db.prepare("UPDATE diag_events SET status='resolved',resolved_at=? WHERE id=? AND project_id IS ?").run(now(),id,projectId);return this.listDiagnostics({projectId,status:'resolved'}).find(d=>d.id===id)??null;}
 pruneDiagnostics({before=new Date(Date.now()-30*86400000).toISOString()}={}){return this.db.prepare("DELETE FROM diag_events WHERE status='resolved' AND resolved_at<?").run(before);}
 integrityCheck(){return this.db.prepare('PRAGMA integrity_check').all().every(r=>r.integrity_check==='ok');}
 checkpoint(){return this.db.prepare('PRAGMA wal_checkpoint(TRUNCATE)').get();}
 backup(destination){return backup(this.db,destination);}
}
export default BrainStore;
