import {parseTree,getNodeValue,findNodeAtLocation,modify,applyEdits} from 'jsonc-parser';
import {parse as parseToml} from 'smol-toml';
import {isDeepStrictEqual} from 'node:util';
const begin='<!-- hermit:v8:start -->',end='<!-- hermit:v8:end -->';
export function parseConfig(text,format){try{if(format==='toml')return parseToml(text);const errors=[],root=parseTree(text,errors,{allowTrailingComma:true,disallowComments:false});if(errors.length||!root||root.type!=='object')throw new Error('invalid object');const walk=n=>{if(n.type==='object'){const keys=n.children.map(p=>p.children[0].value);if(new Set(keys).size!==keys.length)throw new Error('duplicate keys');}for(const x of n.children||[])walk(x);};walk(root);return JSON.parse(JSON.stringify(getNodeValue(root)));}catch{throw new Error('HERMIT_CONFIG_PARSE: invalid '+format);}}
const jsonPath=a=>[a==='opencode'?'mcp':'mcpServers','hermit-graph'];
function rawNode(text,path){const n=findNodeAtLocation(parseTree(text),path);return n?text.slice(n.offset,n.offset+n.length):null;}
export function patchConfig(text,adapter,config){const source=text??(adapter.format==='toml'?'':'{}\n'),parsed=parseConfig(source,adapter.format);if(JSON.stringify(parsed).includes('MEMORY_FILE_PATH'))throw new Error('HERMIT_LEGACY_CONFIG: remove MEMORY_FILE_PATH explicitly after backup');if(adapter.format==='toml'){const old=parsed.mcp_servers?.['hermit-graph'];if(old){if(isDeepStrictEqual(old,config))return {text:source,ownership:null};throw new Error('HERMIT_CONFIG_CONFLICT: existing hermit-graph');}const block=`# hermit:v8:start\n[mcp_servers.hermit-graph]\ncommand = ${JSON.stringify(config.command)}\nargs = ${JSON.stringify(config.args)}\n[mcp_servers.hermit-graph.env]\nHERMIT_DATA_DIR = ${JSON.stringify(config.env.HERMIT_DATA_DIR)}\n# hermit:v8:end\n`;const output=source+(source&&!source.endsWith('\n')?'\n':'')+block;parseConfig(output,'toml');return {text:output,ownership:{kind:'block',block}};}
 const path=jsonPath(adapter.id),value=adapter.id==='opencode'?{type:'local',command:[config.command,...config.args],environment:config.env,enabled:true}:config;const old=parsed[path[0]]?.[path[1]];if(old!==undefined){if(isDeepStrictEqual(old,value))return {text:source,ownership:null};throw new Error('HERMIT_CONFIG_CONFLICT: existing hermit-graph');}if(parsed[path[0]]!==undefined&&(typeof parsed[path[0]]!=='object'||parsed[path[0]]===null||Array.isArray(parsed[path[0]])))throw new Error('HERMIT_CONFIG_PARSE: MCP table is not an object');const output=applyEdits(source,modify(source,path,value,{formattingOptions:{insertSpaces:true,tabSize:2,eol:source.includes('\r\n')?'\r\n':'\n'}}));parseConfig(output,adapter.format);return {text:output,ownership:{kind:'json',path,raw:rawNode(output,path)}};
}
export function patchInstructions(text){const source=text??'',hasBegin=source.includes(begin),hasEnd=source.includes(end);if(hasBegin||hasEnd){if(source.split(begin).length!==2||source.split(end).length!==2||source.indexOf(begin)>source.indexOf(end))throw new Error('HERMIT_CONFIG_PARSE: malformed instruction markers');return {text:source,ownership:null};}const block=begin+'\nUse hermit_session_start with this project path before recalling project knowledge. Save verified knowledge through Hermit MCP tools.\n'+end+'\n';return {text:source+(source&&!source.endsWith('\n')?'\n':'')+block,ownership:{kind:'block',block}};}
export function removeOwned(text,ownership,format){if(!ownership)throw new Error('HERMIT_OWNERSHIP_CONFLICT');if(ownership.kind==='file')throw new Error('HERMIT_OWNERSHIP_CONFLICT: hook file changed');if(ownership.kind==='composite'){let result=text;for(const item of [...ownership.items].reverse())result=removeOwned(result,item,format);return result;}if(ownership.kind==='json-array'){parseConfig(text,format);const node=findNodeAtLocation(parseTree(text),ownership.path);const matches=(node?.children||[]).map((n,i)=>({i,raw:text.slice(n.offset,n.offset+n.length)})).filter(n=>n.raw===ownership.raw);if(matches.length!==1)throw new Error('HERMIT_OWNERSHIP_CONFLICT: hook entry changed');return applyEdits(text,modify(text,[...ownership.path,matches[0].i],undefined,{formattingOptions:{insertSpaces:true,tabSize:2}}));}if(ownership.kind==='block'){if(text.split(ownership.block).length!==2)throw new Error('HERMIT_OWNERSHIP_CONFLICT: marked content changed');const result=text.replace(ownership.block,'');if(format==='toml')parseConfig(result,'toml');return result;}parseConfig(text,format);if(rawNode(text,ownership.path)!==ownership.raw)throw new Error('HERMIT_OWNERSHIP_CONFLICT: MCP entry changed');return applyEdits(text,modify(text,ownership.path,undefined,{formattingOptions:{insertSpaces:true,tabSize:2}}));}

export function patchHooks(text,adapter,command){
 const source=text??(adapter.format==='toml'?'':'{}\n');const parsed=parseConfig(source,adapter.format);const events=['SessionStart','SessionEnd'];
 if(adapter.format==='toml'){
  const marker='# hermit:v8:hooks:start',end='# hermit:v8:hooks:end';
  const block=marker+'\n'+events.map(event=>`[[hooks.${event}]]\n[[hooks.${event}.hooks]]\ntype = "command"\ncommand = ${JSON.stringify(command)}\n`).join('')+end+'\n';
  if(source.includes(marker)){if(source.includes(block))return {text:source,ownership:null};throw new Error('HERMIT_CONFIG_CONFLICT: edited hook block');}
  const output=source+(source&&!source.endsWith('\n')?'\n':'')+block;parseConfig(output,'toml');return {text:output,ownership:{kind:'block',block}};
 }
 let output=source;const owned=[];
 for(const event of events){const path=['hooks',event],current=parseConfig(output,'jsonc').hooks?.[event];if(current!==undefined&&!Array.isArray(current))throw new Error('HERMIT_CONFIG_PARSE: hook event must be array');const entry={hooks:[{type:'command',command}]};if(current?.some(x=>isDeepStrictEqual(x,entry)))continue;const index=current?.length||0;output=applyEdits(output,modify(output,current?[...path,index]:path,current?entry:[entry],{isArrayInsertion:!!current,formattingOptions:{insertSpaces:true,tabSize:2}}));owned.push({kind:'json-array',path,raw:rawNode(output,[...path,index])});}
 return {text:output,ownership:owned.length?{kind:'composite',items:owned}:null};
}
