import {existsSync,mkdirSync,readdirSync,unlinkSync,mkdtempSync,rmSync,statSync,realpathSync} from 'node:fs';
import {join,resolve,isAbsolute,dirname} from 'node:path';
import {homedir,tmpdir} from 'node:os';
import {randomUUID} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StdioClientTransport,getDefaultEnvironment} from '@modelcontextprotocol/sdk/client/stdio.js';
import {selectAdapters,AGENT_ADAPTERS} from './agent-adapters.mjs';
import {patchConfig,patchInstructions,removeOwned,parseConfig,patchHooks} from './config-patcher.mjs';
import {hash,readOptional,atomicWrite,writeManifest,readManifest} from './setup-manifest.mjs';
import {writeCapsule} from '../diagnostics/crash-capsule.mjs';
import {resolvePaths} from '../storage/paths.mjs';
import {canonicalTarget,withMaintenance,assertMaintenanceLock} from '../maintenance/maintenance-lock.mjs';
const fail=(code)=>{throw Object.assign(new Error(code),{code});};
export async function smokeServer({serverPath,nodePath,projectRoot}){const data=mkdtempSync(join(tmpdir(),'hermit-setup-smoke-'));const client=new Client({name:'hermit-setup-verifier',version:'8'}),transport=new StdioClientTransport({command:nodePath,args:[serverPath],cwd:projectRoot,env:{...getDefaultEnvironment(),HERMIT_DATA_DIR:data},stderr:'pipe'});transport.stderr?.on('data',()=>{});let timer;try{await Promise.race([(async()=>{await client.connect(transport);const result=await client.listTools();if(!result.tools.some(x=>x.name==='hermit_session_start'))fail('HERMIT_MCP_SMOKE_FAILED');})(),new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error('HERMIT_MCP_SMOKE_TIMEOUT')),15000);})]);return true;}finally{clearTimeout(timer);await client.close().catch(()=>{});rmSync(data,{recursive:true,force:true});}}
export class SetupService {
 constructor(options={}){const paths=resolvePaths();this.context={home:homedir(),activeAgent:process.env.CLAUDECODE?'claude':process.env.CODEX_THREAD_ID?'codex':null,projectRoot:process.cwd(),dataRoot:paths.dataRoot,serverPath:fileURLToPath(new URL('../../hermit-mcp-server.mjs',import.meta.url)),nodePath:process.execPath,...options};for(const key of ['home','projectRoot','dataRoot','serverPath','nodePath']){if(!isAbsolute(this.context[key]))fail('HERMIT_SETUP_ABSOLUTE_PATH_REQUIRED');this.context[key]=["serverPath","nodePath"].includes(key)?realpathSync(this.context[key]):canonicalTarget(this.context[key]);}this.manifestDir=join(this.context.dataRoot,'setup-manifests');this.dbPath=join(this.context.dataRoot,'brain.db');this.smoke=options.smoke||smokeServer;this.afterWrite=options.afterWrite;this.issued=new Map();}
 plan({agent='auto'}={}){if(!existsSync(this.context.serverPath)||!statSync(this.context.serverPath).isFile())fail('HERMIT_SERVER_MISSING');const adapters=selectAdapters(agent,this.context),files=[];const add=(path,format,agent,patch)=>{path=canonicalTarget(path);const before=readOptional(path),result=patch(before);if(result.text!==before)files.push({path,format,agent,before,after:result.text,beforeHash:hash(before),afterHash:hash(result.text),ownership:result.ownership});};let unownedRoot=false;
if(adapters.length){const sentinel=join(this.context.dataRoot,'.hermit-data-root.json');const existing=readOptional(sentinel);if(existing!==null){let parsed;try{parsed=JSON.parse(existing);}catch{fail('HERMIT_UNOWNED_DATA_ROOT');}if(parsed.owner!=='hermit-graph'||parsed.version!==1)fail('HERMIT_UNOWNED_DATA_ROOT');}else{if([this.context.home,this.context.projectRoot,fileURLToPath(new URL('../../../',import.meta.url))].map(p=>resolve(p)).includes(this.context.dataRoot)||dirname(this.context.dataRoot)===this.context.dataRoot)fail('HERMIT_UNSAFE_DATA_ROOT');if(existsSync(this.context.dataRoot)&&readdirSync(this.context.dataRoot).length)fail('HERMIT_UNOWNED_DATA_ROOT');unownedRoot=true;add(sentinel,'json','data-root',()=>({text:JSON.stringify({owner:'hermit-graph',version:1},null,2)+'\n',ownership:{kind:'file'}}));}}
const config={command:this.context.nodePath,args:[this.context.serverPath],env:{HERMIT_DATA_DIR:this.context.dataRoot}};for(const a of adapters){
 let command;
 if(a.hookFile){const path=a.hookFile(this.context),packageRoot=fileURLToPath(new URL('../../../',import.meta.url));const shim=`'use strict';\nprocess.env.HERMIT_DATA_DIR=${JSON.stringify(this.context.dataRoot)};\nprocess.env.HERMIT_PACKAGE_ROOT=${JSON.stringify(packageRoot)};\nrequire(${JSON.stringify(join(packageRoot,'catalog','hooks','session-hook-'+a.id+'.cjs'))});\n`;add(path,'script',a.id,t=>{if(t!==null&&t!==shim)fail('HERMIT_CONFIG_CONFLICT');return {text:shim,ownership:{kind:'file'}};});if(/[\r\n\x22\x24\x60%]/.test(this.context.nodePath+path))fail('HERMIT_UNSAFE_HOOK_COMMAND_PATH');command=JSON.stringify(this.context.nodePath)+' '+JSON.stringify(path);}
 add(a.config(this.context),a.format,a.id,t=>{const mcp=patchConfig(t,a,config);if(!a.hookFile||a.hookConfig(this.context)!==a.config(this.context))return mcp;const hooks=patchHooks(mcp.text,a,command);return {text:hooks.text,ownership:{kind:'composite',items:[mcp.ownership,hooks.ownership].filter(Boolean)}};});
 if(a.hookFile&&a.hookConfig(this.context)!==a.config(this.context))add(a.hookConfig(this.context),'jsonc',a.id,t=>patchHooks(t,{...a,format:'jsonc'},command));
}if(adapters.length)add(join(this.context.projectRoot,'AGENTS.md'),'markdown','shared',patchInstructions);return this.issue({operation:'setup',unownedRoot,agents:adapters.map(a=>a.id),capabilities:adapters.map(a=>({id:a.id,...a.capabilities})),files,serverPath:this.context.serverPath,serverHash:hash(readOptional(this.context.serverPath)),dataRoot:this.context.dataRoot});}
 issue(plan){const p={version:1,id:randomUUID(),...plan};this.issued.set(p.id,JSON.stringify(p));return p;}
 check(plan){if(plan.unownedRoot&&existsSync(this.context.dataRoot)&&readdirSync(this.context.dataRoot).some(name=>name!=='.brain.db.maintenance'))fail('HERMIT_PLAN_STALE');if(this.issued.get(plan.id)!==JSON.stringify(plan))fail('HERMIT_PLAN_UNTRUSTED');for(const f of plan.files){if(canonicalTarget(f.path)!==f.path||hash(readOptional(f.path))!==f.beforeHash)fail('HERMIT_PLAN_STALE');}if(plan.serverHash&&hash(readOptional(plan.serverPath))!==plan.serverHash)fail('HERMIT_PLAN_STALE');}
 async apply(plan){if(plan.operation!=='setup')fail('HERMIT_INVALID_SETUP_PLAN');return this.execute(plan);}
 async execute(plan,options={}){const action=async()=>{this.check(plan);if(!plan.files.length)return {status:'unchanged',manifest:null,files:0};mkdirSync(this.manifestDir,{recursive:true});const manifestPath=join(this.manifestDir,plan.id+'.json'),backupDir=join(this.manifestDir,plan.id);mkdirSync(backupDir);const manifest={...plan,status:'prepared',createdAt:new Date().toISOString()};for(let i=0;i<plan.files.length;i++)if(plan.files[i].before!==null)atomicWrite(join(backupDir,i+'.backup'),plan.files[i].before);writeManifest(manifestPath,manifest);const changed=[];try{for(const f of plan.files){if(hash(readOptional(f.path))!==f.beforeHash)fail('HERMIT_PLAN_STALE');if(f.after===null)unlinkSync(f.path);else atomicWrite(f.path,f.after);changed.push(f);await this.afterWrite?.(f,changed.length);if(hash(readOptional(f.path))!==f.afterHash)fail('HERMIT_SETUP_VERIFY_FAILED');}if(plan.operation==='setup'&&await this.smoke(this.context)!==true)fail('HERMIT_MCP_SMOKE_FAILED');manifest.status='applied';writeManifest(manifestPath,manifest);if(plan.operation==='uninstall')for(const source of plan.sources){const m=readManifest(source);m.uninstalledAgents=[...new Set([...(m.uninstalledAgents||[]),...plan.agents])];if(m.agents.every(a=>m.uninstalledAgents.includes(a)))m.status=m.files.some(f=>f.agent==='shared')&&!plan.files.some(f=>f.agent==='shared')?'applied':'uninstalled';writeManifest(source,m);}return {status:'applied',manifest:manifestPath,files:changed.length};}catch(cause){const rollbackErrors=[];for(const f of changed.reverse()){try{if(hash(readOptional(f.path))!==f.afterHash)fail('HERMIT_ROLLBACK_CONFLICT');if(f.before===null){if(existsSync(f.path))unlinkSync(f.path);}else atomicWrite(f.path,f.before);}catch{rollbackErrors.push(f.path);}}manifest.status=rollbackErrors.length?'rollback-failed':'rolled-back';manifest.rollbackErrors=rollbackErrors;writeManifest(manifestPath,manifest);const diagnostic=writeCapsule({directory:join(this.context.dataRoot,'crash-spool'),metadata:{code:'HERMIT_SETUP_CONFLICT',component:'setup',phase:'rollback'}});throw Object.assign(new Error('HERMIT_SETUP_FAILED: '+cause.message),{code:'HERMIT_SETUP_FAILED',cause,correlationId:diagnostic.id||plan.id,diagnosticRef:diagnostic.path||null,recoveryManifest:manifestPath,diagnosticsDegraded:!diagnostic.durable,rollbackErrors});}};if(options.maintenanceLock){assertMaintenanceLock(options.maintenanceLock,this.dbPath);return action();}return withMaintenance(this.dbPath,action);}
 verify(path){const m=readManifest(path);const failures=m.files.filter(f=>hash(readOptional(f.path))!==f.afterHash).map(f=>f.path);return {ok:failures.length===0,failures};}
 planUninstall({agent='all'}={}){const agents=selectAdapters(agent==='auto'?'all':agent,this.context).map(a=>a.id);const sources=[],files=[],seen=new Set();const manifests=existsSync(this.manifestDir)?readdirSync(this.manifestDir).filter(f=>f.endsWith('.json')).map(f=>join(this.manifestDir,f)):[];const active=manifests.map(path=>({path,m:readManifest(path)})).filter(({m})=>m.operation==='setup'&&m.status==='applied');const remaining=active.some(({m})=>m.agents.some(a=>!agents.includes(a)&&!m.uninstalledAgents?.includes(a)));for(const {path,m} of active){if(!m.agents.some(a=>agents.includes(a)&&!m.uninstalledAgents?.includes(a))&&(remaining||!m.files.some(f=>f.agent==='shared')))continue;sources.push(path);for(const f of m.files){if(f.agent==='data-root'){if(f.path!==join(this.context.dataRoot,'.hermit-data-root.json'))fail('HERMIT_MANIFEST_TARGET');continue;}if(f.agent==='shared'?remaining:!agents.includes(f.agent))continue;const adapter=AGENT_ADAPTERS.find(a=>a.id===f.agent);const allowed=f.agent==='shared'?[join(this.context.projectRoot,'AGENTS.md')]:[adapter?.config(this.context),adapter?.hookFile?.(this.context),adapter?.hookConfig?.(this.context)].filter(Boolean);if(!allowed.some(p=>canonicalTarget(p)===f.path))fail('HERMIT_MANIFEST_TARGET');if(seen.has(f.path))continue;seen.add(f.path);if(canonicalTarget(f.path)!==f.path)fail('HERMIT_UNSAFE_PATH');const before=readOptional(f.path);if(before===null)continue;let after;if(hash(before)===f.afterHash)after=f.before;else after=removeOwned(before,f.ownership,f.format);files.push({...f,before,after,beforeHash:hash(before),afterHash:hash(after)});}}return this.issue({operation:'uninstall',agents,files,sources,dataRoot:this.context.dataRoot});}
 async uninstall(plan,options={}){if(plan.operation!=='uninstall')fail('HERMIT_INVALID_SETUP_PLAN');return this.execute(plan,options);}
}
