import {DatabaseSync,backup} from 'node:sqlite';
import {existsSync,mkdirSync,readFileSync,writeFileSync,copyFileSync,renameSync,unlinkSync,readdirSync,statSync} from 'node:fs';
import {join,dirname,resolve,parse} from 'node:path';
import {homedir} from 'node:os';
import {fileURLToPath} from 'node:url';
import {createHash,randomUUID} from 'node:crypto';
import {canonicalTarget,withMaintenance,acquireRuntimeLease,assertMaintenanceLock} from './maintenance-lock.mjs';
const fail=(code,message)=>{throw Object.assign(new Error(message),{code});};
const hash=path=>createHash('sha256').update(readFileSync(path)).digest('hex');
export function probeDatabase(path,{schema=8}={}){const db=new DatabaseSync(path,{readOnly:true});try{const version=db.prepare('PRAGMA user_version').get().user_version;if(version!==schema)fail('HERMIT_SCHEMA_UNSUPPORTED',`Expected schema ${schema}; found ${version}`);if(db.prepare('PRAGMA integrity_check').all().some(r=>r.integrity_check!=='ok')||db.prepare('PRAGMA foreign_key_check').all().length)fail('HERMIT_BACKUP_INVALID','Database integrity check failed');return {schemaVersion:version,integrity:'ok'};}finally{db.close();}}
export function verifyBackup(directory){const root=canonicalTarget(directory),manifest=JSON.parse(readFileSync(join(root,'manifest.json'),'utf8'));if(manifest.format!=='hermit-v8-backup'||manifest.schemaVersion!==8||manifest.integrity!=='ok'||manifest.database!=='brain.db'||manifest.sha256!==hash(join(root,'brain.db')))fail('HERMIT_BACKUP_INVALID','Backup manifest or content hash mismatch');return {...manifest,...probeDatabase(join(root,'brain.db'))};}
export async function createBackup(dbPath,directory,{maintenanceLock}={}){if(maintenanceLock)assertMaintenanceLock(maintenanceLock,dbPath);const lease=maintenanceLock?null:acquireRuntimeLease(dbPath);try{return await createBackupLocked(dbPath,directory);}finally{lease?.release();}}
async function createBackupLocked(dbPath,directory){const source=canonicalTarget(dbPath),dest=canonicalTarget(directory);if(existsSync(dest))fail('HERMIT_BACKUP_EXISTS','Backup destination must be fresh');mkdirSync(dest,{recursive:true});const db=new DatabaseSync(source,{readOnly:true});try{await backup(db,join(dest,'brain.db'));}finally{db.close();}const manifest={format:'hermit-v8-backup',id:randomUUID(),createdAt:new Date().toISOString(),database:'brain.db',...probeDatabase(join(dest,'brain.db')),sha256:hash(join(dest,'brain.db'))};writeFileSync(join(dest,'manifest.json'),JSON.stringify(manifest,null,2),{flag:'wx'});verifyBackup(dest);return {directory:dest,...manifest};}
export function listBackups(root){if(!existsSync(root))return [];return readdirSync(root).filter(name=>statSync(join(root,name)).isDirectory()).map(name=>{const directory=join(root,name);try{return {directory,...verifyBackup(directory),valid:true};}catch{return {directory,valid:false};}});}
function checkpoint(dbPath){const db=new DatabaseSync(dbPath);try{const result=db.prepare('PRAGMA wal_checkpoint(TRUNCATE)').get();if(result.busy)fail('HERMIT_RUNTIME_ACTIVE','SQLite handles are not quiescent');db.exec('BEGIN EXCLUSIVE; COMMIT;');}finally{db.close();}}
export async function replaceDatabase(dbPath,replacement,{postSwap=probeDatabase,maintenanceLock}={}){
 assertMaintenanceLock(maintenanceLock,dbPath);
 const target=canonicalTarget(dbPath),next=canonicalTarget(replacement);if(dirname(target)!==dirname(next))fail('HERMIT_UNSAFE_PATH','Replacement must share the database directory');probeDatabase(next);checkpoint(target);const previous=`${target}.rollback-${randomUUID()}`,journal=`${target}.swap-recovery.json`;writeFileSync(journal,JSON.stringify({target,previous,sha256:hash(target)}),{flag:'wx',flush:true});renameSync(target,previous);
 try{renameSync(next,target);await postSwap(target);unlinkSync(journal);return {dbPath:target,rollbackPath:previous};}catch(error){if(existsSync(target))renameSync(target,`${target}.failed-${randomUUID()}`);renameSync(previous,target);unlinkSync(journal);throw error;}
}
export function previewRestore(dbPath,directory){const verified=verifyBackup(directory);return {operation:'restore',dbPath:canonicalTarget(dbPath),backup:canonicalTarget(directory),sha256:verified.sha256};}
export async function restoreBackup(dbPath,directory,{confirmation,backupDirectory,postSwap}={}){const plan=previewRestore(dbPath,directory);if(confirmation!==JSON.stringify(plan))fail('HERMIT_CONFIRMATION_REQUIRED','Confirm the exact restore preview JSON');return withMaintenance(dbPath,async lock=>{verifyBackup(directory);const rollbackBackup=await createBackup(dbPath,backupDirectory||join(dirname(dbPath),'backups',`pre-restore-${randomUUID()}`),{maintenanceLock:lock});const next=`${dbPath}.replacement-${randomUUID()}`;copyFileSync(join(directory,'brain.db'),next);if(hash(next)!==plan.sha256)fail('HERMIT_BACKUP_INVALID','Backup changed during restore');return {...await replaceDatabase(dbPath,next,{postSwap,maintenanceLock:lock}),rollbackBackup,evidence:lock.evidence};});}
export function assertOwnedRoot(root,{forbiddenRoots=[]}={}){const canonical=canonicalTarget(root);const forbidden=[parse(canonical).root,homedir(),process.cwd(),fileURLToPath(new URL('../../../',import.meta.url)),...forbiddenRoots].map(p=>resolve(p).toLowerCase());if(forbidden.includes(canonical.toLowerCase()))fail('HERMIT_UNSAFE_PATH','Refusing root, home, workspace or package directory');const sentinel=JSON.parse(readFileSync(canonicalTarget(join(canonical,'.hermit-data-root.json')),'utf8'));if(sentinel.owner!=='hermit-graph'||sentinel.version!==1)fail('HERMIT_UNOWNED_ROOT','Matching Hermit ownership sentinel required');return canonical;}
