import {DIAGNOSTICS_SCHEMA_SQL} from '../diagnostics/store.mjs';
import {CURRENT_SCHEMA_REVISION} from '../storage/schema-v8.mjs';
import {SetupService} from '../setup/setup-service.mjs';
import {DatabaseSync} from 'node:sqlite';
import {join,dirname} from 'node:path';
import {existsSync,readFileSync,copyFileSync,renameSync,lstatSync,readdirSync} from 'node:fs';
import {randomUUID,createHash} from 'node:crypto';
import {assertOwnedRoot,createBackup,replaceDatabase} from './backup-service.mjs';
import {withMaintenance,canonicalTarget} from './maintenance-lock.mjs';
const fail=(code,message)=>{throw Object.assign(new Error(message),{code});};
const scopes=['knowledge','diagnostics','code-cache','models','integrations','all'];
function tree(path){if(!existsSync(path))return [];canonicalTarget(path);if(lstatSync(path).isDirectory())return [{path,kind:'directory'},...readdirSync(path).flatMap(name=>tree(join(path,name)))];return [{path,kind:'file',sha256:createHash('sha256').update(readFileSync(path)).digest('hex')}];}
export function previewReset({dataRoot,dbPath=join(dataRoot,'brain.db'),scope,forbiddenRoots=[],projectRoot=process.cwd(),home}){if(!scopes.includes(scope))fail('HERMIT_VALIDATION','Unknown reset scope');const root=assertOwnedRoot(dataRoot,{forbiddenRoots});const target=canonicalTarget(dbPath);if(target!==join(root,'brain.db'))fail('HERMIT_UNSAFE_PATH','Reset database must be owned root brain.db');const selected=scope==='all'?scopes.filter(s=>s!=='all'):[scope];const setup=selected.includes('integrations')?new SetupService({dataRoot:root,projectRoot,...(home?{home}:{})}):null;const uninstall=setup?.planUninstall({agent:'all'});const integrations=uninstall?{files:uninstall.files.map(({path,beforeHash,afterHash})=>({path,beforeHash,afterHash})),sources:uninstall.sources}:null;const db=new DatabaseSync(target,{readOnly:true});let tables;try{let revision;try{revision=Number(db.prepare("SELECT value FROM schema_meta WHERE key='revision'").get()?.value);}catch{}if(revision!==CURRENT_SCHEMA_REVISION)fail('HERMIT_UPGRADE_REQUIRED','Upgrade before reset');tables=db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'").all().map(r=>r.name);const wanted=selected.flatMap(s=>s==='knowledge'?['scan_runs','relations','observations','change_events','entities','entity_fts',...tables.filter(t=>/^(embedding|vector|semantic_vectors)/.test(t))]:s==='diagnostics'?tables.filter(t=>t.startsWith('diag_')):[]);tables=[...new Set(wanted)].filter(t=>tables.includes(t)).map(name=>({name,rows:Number(db.prepare(`SELECT count(*) AS n FROM "${name.replaceAll('"','""')}"`).get().n)}));}finally{db.close();}const paths=selected.filter(s=>['models','code-cache'].includes(s)).map(s=>join(root,s));return {operation:'reset',scope,dataRoot:root,dbPath:target,tables,paths:paths.flatMap(tree),roots:paths,integrations};}
export async function applyReset(options){const plan=previewReset(options);if(options.confirmation!==JSON.stringify(plan))fail('HERMIT_CONFIRMATION_REQUIRED','Confirm exact reset preview JSON including row counts and absolute paths');return withMaintenance(plan.dbPath,async lock=>{if(JSON.stringify(previewReset(options))!==JSON.stringify(plan))fail('HERMIT_PLAN_STALE','Reset targets changed after preview');const backup=await createBackup(plan.dbPath,options.backupDirectory||join(plan.dataRoot,'backups',`pre-reset-${randomUUID()}`),{maintenanceLock:lock});const replacement=`${plan.dbPath}.replacement-${randomUUID()}`;copyFileSync(join(backup.directory,'brain.db'),replacement);const db=new DatabaseSync(replacement);try{db.exec('PRAGMA foreign_keys=OFF; BEGIN IMMEDIATE');if(plan.tables.some(t=>t.name==='entities')&&db.prepare("SELECT name FROM sqlite_master WHERE name='diag_fingerprint'").get())db.exec('UPDATE diag_fingerprint SET incident_entity_id=NULL');for(const {name} of plan.tables)db.exec(`DELETE FROM "${name.replaceAll('"','""')}"`);if(plan.tables.some(t=>t.name==='diag_meta'))db.exec(DIAGNOSTICS_SCHEMA_SQL);db.exec('COMMIT');}finally{db.close();}const moved=[];let swapped;try{for(const path of plan.roots)if(existsSync(path)){canonicalTarget(path);const retained=`${path}.reset-backup-${randomUUID()}`;renameSync(path,retained);moved.push({path,retained});}swapped=await replaceDatabase(plan.dbPath,replacement,{postSwap:options.postSwap,maintenanceLock:lock});let integrationResult=null;if(plan.integrations){const setup=new SetupService({dataRoot:plan.dataRoot,projectRoot:options.projectRoot||process.cwd(),...(options.home?{home:options.home}:{})});const uninstall=setup.planUninstall({agent:'all'});const current={files:uninstall.files.map(({path,beforeHash,afterHash})=>({path,beforeHash,afterHash})),sources:uninstall.sources};if(JSON.stringify(current)!==JSON.stringify(plan.integrations))fail('HERMIT_PLAN_STALE','Integration targets changed');integrationResult=await setup.uninstall(uninstall,{maintenanceLock:lock});}return {...swapped,backup,retained:moved,integrations:integrationResult,evidence:lock.evidence};}catch(error){if(swapped){renameSync(plan.dbPath,`${plan.dbPath}.failed-${randomUUID()}`);renameSync(swapped.rollbackPath,plan.dbPath);}for(const {path,retained} of moved.reverse())renameSync(retained,path);throw error;}});}
