import {DatabaseSync} from 'node:sqlite';
import {join,dirname} from 'node:path';
import {copyFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {withMaintenance,canonicalTarget} from './maintenance-lock.mjs';
import {createBackup,probeDatabase,replaceDatabase,restoreBackup,previewRestore} from './backup-service.mjs';
import {CURRENT_SCHEMA_REVISION} from '../storage/schema-v8.mjs';
export {CURRENT_SCHEMA_REVISION};
const fail=(code,message)=>{throw Object.assign(new Error(message),{code});};
export function upgradePlan(dbPath){const path=canonicalTarget(dbPath),db=new DatabaseSync(path,{readOnly:true});try{const schema=db.prepare('PRAGMA user_version').get().user_version;let revision=1;try{revision=Number(db.prepare("SELECT value FROM schema_meta WHERE key='revision'").get()?.value??1);}catch{}return {operation:'upgrade',dbPath:path,schemaVersion:schema,fromRevision:revision,toRevision:CURRENT_SCHEMA_REVISION,supported:schema===8&&revision<=CURRENT_SCHEMA_REVISION,requiresShutdown:true,action:revision===CURRENT_SCHEMA_REVISION?'verify':'upgrade'};}finally{db.close();}}
export async function applyUpgrade(dbPath,{confirmation,backupDirectory,migrate,postSwap}={}){const plan=upgradePlan(dbPath);if(!plan.supported)fail('HERMIT_SCHEMA_UNSUPPORTED','Legacy/newer schemas require their matching runtime; no semantic import is provided');if(confirmation!==JSON.stringify(plan))fail('HERMIT_CONFIRMATION_REQUIRED','Confirm exact upgrade preview JSON');return withMaintenance(dbPath,async lock=>{if(JSON.stringify(upgradePlan(dbPath))!==JSON.stringify(plan))fail('HERMIT_PLAN_STALE','Schema changed after preview');if(plan.action==='verify')return verifyUpgrade(dbPath);const backup=await createBackup(dbPath,backupDirectory||join(dirname(dbPath),'backups',`pre-upgrade-${randomUUID()}`),{maintenanceLock:lock});const replacement=`${dbPath}.replacement-${randomUUID()}`;copyFileSync(join(backup.directory,'brain.db'),replacement);const db=new DatabaseSync(replacement);try{db.exec('PRAGMA foreign_keys=ON; BEGIN IMMEDIATE');const migration=migrate??(await import('../storage/schema-v8.mjs')).initializeExtendedSchema;await migration(db);db.exec("CREATE TABLE IF NOT EXISTS schema_meta(key TEXT PRIMARY KEY,value TEXT NOT NULL) STRICT");db.prepare("INSERT INTO schema_meta(key,value) VALUES('revision',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").run(String(CURRENT_SCHEMA_REVISION));db.exec('COMMIT');}catch(e){try{db.exec('ROLLBACK');}catch{}throw e;}finally{db.close();}verifyUpgrade(replacement);return {...await replaceDatabase(dbPath,replacement,{postSwap:postSwap??verifyUpgrade,maintenanceLock:lock}),backup,evidence:lock.evidence};});}
export function verifyUpgrade(dbPath){const integrity=probeDatabase(dbPath),plan=upgradePlan(dbPath);if(plan.fromRevision!==CURRENT_SCHEMA_REVISION)fail('HERMIT_UPGRADE_REQUIRED','Explicit hermit upgrade apply is required');return {...integrity,revision:plan.fromRevision};}
export function rollbackUpgrade(dbPath,backupDirectory,options){return restoreBackup(dbPath,backupDirectory,options);}
export {previewRestore as previewUpgradeRollback};
